@startuml Sequence

!include Pirates\Pirate.puml
!include Pirates\WomanPirate.puml

skinparam Participant {
    BackgroundColor Transparent
    BorderColor Transparent
}

participant "<$Pirate_100>\nBob" as Bob
participant "<$WomanPirate_100>\nAlice" as Alice

Bob -> Alice : Hello

@enduml