sprite $JollyRoger_200 [200x148/16z] {
xPo7akey3uObkSLDkl-h_Gi1RHoSveLTpim-Kxvwm6zKBCaE0F377t_yyGTPPrSG_6EOaAjqo0x_9HMPPGkE1Fy254fbsQDOk86VR8cqhu7_3I4JoncgWqy6
9pb9THyluuHV2Kkrdoe2CCe5glbK8L4kKGW-aYWNIGWVY9UhS83FW-QgW-K2bU3ZA3UNHxb4-ZWXuIO39hb6_B0ztR28L2Iv27lu932921F8PTXyN90xY2oN
oV0vp65192C468VWjIJv7sX4-Q7aczwHTD7A46wmd0DmvRNsGRxfS394Wb4AGuFvPgLZv3iwU7pFAj1W9S1tc1sAl8m1On2BNwTDjl0DRePW33-h8mkR9sML
lbkKL9X-L8TXAPry4s6SAl_3WFoa3kojEMdw6m5dSoGPP7ZhdNgEKRuNvi7A80K6i5M4JNyb-9rE4AiiuCDvYJBcqRdx0B1ecpccWmD92_V4S4-V6ote_4R6
OJ-i8uAJBwAvcPOIBpNav141mEPM6y9bt5n0R7NNx4Qt3mEXDvYot1qWslAzy31ri-9FSiCCTXy4ang3LdrYvn7PEjw0w8UwxH99ob2xp0iT0JlJe7MzWBUb
P1xIGNLFVsgAps4T4tMVJ-qabWA61_pgaHZzffEha74T5Q45D-mSRjfum1v5z9ishAL2ndK4M44RmOmi5Q1Sxckr69ssYpqLCgIZ_v3CLd9bAG3fSbix2Hza
9AmgP5X7WJL-QxEhKcywqaKPnskSv45ycGxCcetxEgeRSAhz3OBgg13LaJhXmVtqmhEE2IwWCZZj_s_ADAOZzyevyVvP2Drqv8139nDC1sEFCOja8V0Qv-ja
7kwRarqzCqQWAuVFzlJgWem9CGd1tUs8hS3vWypJ7b9kEd1W_pjHFc4PRmjYPyhf-V6TGQC70V1ke3Gg8nsQZaU586jzjNA4XSoqChm_AmI1ogL9QfGl-8eG
b1b-f0XoiNbsarPVouFTY2TbvBEJRTIIUCWYRY7V8f7c5e8PYdF2JDDKEskwuF05J-Ms8I5O3eQUxIEwcE0nN-w3iGpCa2cpR52n5wWAqwcF7pZueKO8fokP
VVzvhtISRwBI5UMAayiM8Td4Dbj62vznN8GyU7mLhX_W9Td2D9lYccBWa39yd1WlNmEnFAGZsqDZO1BXmKj2c2-xLfGDQ3C-OZ3d3hJ73qKjNxM8cHTPynGp
jqcIOZGwExl1oP_S_Y1jBsGa0MM40sokfQPvmNaz2grXcGUh6tMCGd2H90sSSSWl5LOL5uw-C7tx4WTb4MxMOQ_zwKsgXRFa5rpNeZ8o5dTEmwM7paVnP6N1
sp4-NZ65O_7CJlUWFd7uGHRLVmsgbuMGXk9MtPXfNWjUTUpXWrW4U_dw6ed8j5VTYd_utRIln1HkZwsAWM62yBKwWXRfA6vVTSM9HUo-Z9TUzWrFTLsrU5GB
LVeImb92O15kLgFJamxObL7evNTP9xnoR1STG1OBLXZ3FSZzKVfpjV-UnJZarH9An8EQlsAheuW5O46wnqu-q154U6FB6ITSsydAgiQj4Q2Aludnzw9RTdLG
tFk-SQPBbpn3wrXUn4EM2bOaXta6P7Prs2838JveaMtVigsEAkmXIm8lmduERjhKWG2E1wmnR97jo3Fj4hCmGCa6lCXaM2QTT7Np5KxSxnZVPn7sP-nXIm4m
281423uJ0BZDSG6bZUVrJej8f2rxn1FzTkbVKXXtgl5t8ehTi4V5uu_AsrOlBxU6WgvoPsepTNIeOzdqE1Umx7MhfgsQCyfCib07hJ7U6cNgwgW8W2m58CPv
57_x1FfQBfkd_bxRasb0ndYpsWzt-fgv5vO8KvrZ1W6J603Yxls6K3NcCB_xFR38FI6PMhKgBuXaY3otsG30aWXYpwsM_nRJswoXUExTUAk-ut-SVHMfKDZT
wjkvcobLPcBFqjdgtxCKyyRtLbsLmmoCINWfbXrcaPetIqt7NqsQJIB2Qest2Q5uuYNJBFkqrWXy3t1S63pJBxqacEcK4DOEPfK6RoF7y9FluuKYFJZWRcfJ
UEbKxhwvXw-gWKKyl9j-PSth18DfMyP4JrjuDXfNsvNRsxV4MkKHgUq5Ipx82PGMbZJrvr_on21ByjGwbmhfLp88CsxMNroJ2Ok37yHpkwbFibm6RkPe3N5q
QH4j6BcPaAdMdmwIQ69Pp-hC5AR2_JRIvcN2fjJQynTVDgze8dSIafbIBlb6oHxXXico271ml3JcRminO9Bw6Ur65ykCLr6Q9du3MviJo03Wo_6HaydBPQDk
HwonyuicqSYOD62VbJGHNKDRvsG7luY6kwu5GzqvLBPbURi94pTrpIz2aTUba_wq3vT0ZJbiaXiyR-2kQ2dW4NwRTfyefh5IJGJAr1YAiZGTpAVzXap0Pl3F
oM9pK9VDOoVbtyrJYB32vkUPaqtouE5UfhBSLTdVDWQwmfBsHsWSIHFiCY00hMclQnqRm-Letg322_TVlJ2vKu1GADsh64LbL8TxjpAelkT7DQQT6uA1E_Kv
JbKUiDwBiTvx5xnp5izSMc6ny4hGjdT2zwVCd4Zxnw7VXaEgR_en2c9vW8VLlCO9keaN_-wyb29AXHU2W7d_MWB6bPAvXW9Q_lkQBS49dBmdfxMDD-sUtokw
LRii2ai9vlGjcUe8NewsgnOsy4NMIkPrsCPOd8wMLzuw7uttMghisApAYcJlQJkl0iZ09lQjCi28y9P1aAnr5e1qlGe7WiUMmg8mPszfRxplyCq3nGmDZzNp
F6wscQMbHjEMo0hNkDX8iFdzmWplmd0tzVh4yi3gPjvI9thK1KMUP5h4vqB7mjkekjfEeQYTe4Ps0-jEICzIk7X3HCkS6-5zf9LZkPXPj7Kok2ehHLdtuUJh
nW6N7N-bU-1DZzlEWFUuvSVJnjKKpKvLLcJ_y2zZGtsMuVMXTFRYbq7jpKjVrMK8kg29vTc5IAqoVOLMDCjH1FLcHhKaJ_02S7KJ5sqi9KzcLxkjB2loedkt
iVoFMsIvidDtBCoMP_ywU_35Wjh49oLSaoFSgcii0b3y7odbKagj9G3TBSk5hbU7Q_WU3HT_q47tnnQEjdj7DSoJlWOBO4xVL5UCjURBCOoTgd2jPavO8uSk
_Pr3c7Cmj3wrSq2cogOECN0ELnvFfHcOIKMtUl_f8Ze7xkHZBmzAxuKgjpXxf5EkPABSuES3AABch0b685juhKCI8kc_pPqZLKQmSbv7uvWUrXyO8RtYnyHC
Y9rtmgR5f4AKdZPprgVKbCJjSmFRVlSuw5FcPftgimcGvJayv07JMMkeFQQL_H5ouxBV0yrKlcB2Rdwli4S0rUQloP00KAK5mN9FnpXeGoojFMXzgpgxxjl8
ss1P7ehJatspreelBgmH05CJThXWsRJN2U6OUNVoBaIf1i1zPIT-p9dzVhYDamyATiVdWpArhzhP6ASK_yVaIGUMhFPuUtFJCfs_AM1FD30QW_ujEWhkL1dc
oY3FuPmNOx_crv8XuHkQvgEo3Q-yKSJCEuP9RmcGwRLZK9law75JMTyZnE4qfSHNEolQ66EAKJkl7SygmRcG-9R91d2L9rnTlq7uGKoH5GL7tuehEQPSHPCk
_l1z1k7l_aIp__sVtbQBy3UAnYHFU8GV5z9USJNZ6v_24_m2heXItGkYh3Zu7NogNBbwQs0CdslbMYjphSN3o_dZZp_-2m
}

sprite $JollyRoger_100 [100x74/16z] {
xPY7bkmy2eG1vKIz_zDkCDRH7RVLu-cp--VlHiSIXIJmqF-7V_2vr9F4HCJqluLTLlnAfVyrQU1Af_yfad1b05t-fr7WblP_a_ZVvuI9F51momZqFwAZxI8P
yhzoIWN_PxS6Si4MJ-zmz0XMb8ejdTxW8nrmfhS8a1lsq1xkuVmFtFjmWVYXHWAT3ENtAOV3HngoZ6nQw0qLjMFFUFTaffC0fBdURkZgxMKbfwO006qb5mKK
Ya8x8i0qKI3iQq6f0a0hdyy1pUwr94NQ483snN7r-tmK3w1CHM2cZp6I8kmbVht608RRQbHlhlFKe9EYfF3R6RzkP7iGa9sjnG5fvN6v746Zyxs4NcqKl8aa
LRUYPWMGvnMbdkub1fQdQtG0U9CFjuQKCDoOHmMqoSQucGq2BE4Bx1mmP5eWb1JE7jADl_NsRVcD21MeYVX-v34VBtSAZCWx2SJxwA1ojqwQ0j2I1u1qdXX3
SJjJcDfkF_R09l5oA01OeukOA6-YWD_s1NSMwtbbpOke-p9OS528RrqtPAEEfH5Wj4mNkDfe1jCjVMTNLOt-x4HpgMntPg4NkE107TtZfYdX_lA3EbvW9DhX
Lc8lSE7b4DO-mVSIXVPudEIhdQXychcwKCzNJn_rGsbEdyhyLGEUM1GOVJfLhkrkc_fCRyd0xHokw1Qfn4Bg6r6uZ5Vw2l5n-nmk5USGpIKEGiHnOs5QDkjZ
2HFHbymnR1_K7Af3Wb3vDGu95hn9F1DvMIboJbRl-FY7g6FDK2bOkNX4Kk0wp_a8osJcTWA_AX8qFpJgwYrGUHKOHrfyO1Igjecj7WUDCu3Ez8mrHnHhqLUW
-Q4XqyYCMbQG-VXl-K4KQskR5FcwXlNBb9063CTr8_4myz2uH1RPR1tGmcpLwyVugJ0d66TzaSX0z-JqCucLbAPp0uimfb6-0uKv0b1F7y6pfALn6kPS6aDr
Z4n4hXypmbBXFlrcfjETvXA07bxsySOKr8px7EcMZy1LWROCyGCOWQH2LqrZ-emq_VSDG8yy9wnceenFVVewAhQoCBofZ2H47fhvI0YG-FB8qu0ujZKPurcs
7BccCClO4e8k_6L0kPlc0m80bUkght8k4arC94v4wBKKjgSQ-gKiyt5itek5rUAsYWPwXhjyAzZuBI_apnJ5QnZZgSAAEYy9OLzE5Sr2aeR9PCyhm-ud4ama
K2WPn-kBS58OpJD97fWw5W-FbswTtulqiwDqvb9nnqWBPZ2EI5A7qMkqzelf9rGe1bCO07hYbVu6eoTPXvLTNpiZ4ySWtw-zh5Oy9LnJot5WskIOoCNeELk-
NV0-HYzvkzkphIXnAVa0cCYTgouDdBGaimsjSuwZKBdVAZaf-koirNtJWKke2aFjbOXo7gFm_OzIfCAQ3np4zks2Of-xtUtTSM_2YOltxRkzKsQusTinVOEa
DX0405XqDW09mBZx8giDrQ9MgAC6A9WVRADi6zoyaudyxPUbGpzzzi7BxCtWdfM0U4rnB7Ax84fCBT3Y1-r61PHlzA-KtaTv-K2CpgKtDO6FQtdpWSOFj_Zt
JK41nj3zf-mpaVTVU6CrTP_2UK1h5jhXEw10z_JNvzy
}

