sprite $Pirate_200 [200x200/16z] {
rDX7bkCu40JGGCBRkFzfPxfRV2MH88HQaU3Vbis7jCB54bjo2a_d-4_0moM-L8j7i-Ic29wiy8V3CuX6p_0juW5i8t4YyoqzfA0DUe4Vci7IJ1ssLyCTYuK5
lhHv7BHFw4b-E0dNRrjI-QP7at3vjcNvgIhiAVO2rkEvLmQbi_QBgCoZZ4-QfpAMeYfxLNVVi7eWXQUoR57Oof6yP1WsSoSxBIRocxZIAh9nK9Kp4QwisBN2
hjSwpWW0NPOBn7DJ5FwA_2xtVThYVdOtCEQ1D7Ko_Wtk9jnKu5U1sDEPet6p-awgjy0X0vm5t1Hk5VdI19zCuwccCVY-fd4ZnurWJoMUg883UGSi2nI7HySK
7XNqf2sGMlNhRc7taJIFCr9su-SEQPeIDXM-98i1QJVFG_Uh0rMSzqQXSrRivjRYI1ZJiRIMdFns1jqWywLXo5PkgbSOipT-FcUderXNbk14bF6XaaamP6xB
B9cU3tR_N_clTMJkwbbvrglSCUCaCywtvhHOhp9afHnZJnXAjsHMcrpNgj4ZksvinkcgrWJN2RCYZyo0A_r7FpAzyZCkezeicoi5KAwF8sEiNbqYSRRQQRRJ
5jT8XI5xSOcOwKBYMD6hDAIVd_fDNNm3OYGoePVhrhA6yfKbuaP5xah0Iw97hmIaxQ6Kzu8JLtw0qiudkIdlCptH0b0A6n__o1HujfzTNN_9BBckoAcwEHRJ
_yHS1yAhlAwqt9iq-r_jAs08-61YlYJtpbzpIB6iKJUqnCB3h4wDpN5rc-4OHc2K6sRnVownSjr6iY6bwhgL3aQvbyscNOu8yR42NfdhM68wPV_-e4Xl-s5R
XbVAmMrAy8UmkKd4Tld3ScTzzh-JhWDnIzR1Bi1l0aVQHSBYwYJgBNuFlU7lJOG7UYz0Zi7icr-K4G38nF1gNPbJUXDtPHlT4RV-LnfMMlR3FBeqkmY2gW8W
TckNfDNCam39IRbt9E6NYTKuabkVDqKvRljERKmhqRIjpekOKkvoHlvvqpTrHdxLHHI_oflfzOc3Kwr0zKgHSpHqYRyk3itRWOKkgpjAMp_gm49gbcEdouBy
upbW8_QuFyYohMDpegx8DiITGFsfYVYh6S5jPzSebuABGVbdqrdwQVz4PjDgAm2oENGwoqFJzJyqaJIRZ59Oiv00r1oyypwZuV6F5VLbJ5E34e02mFbFJiRK
7oLQkajpHmW2H58P4C4HUM1R0nZyHYDbYbMc0eckHeILWA0h93pjoHJwmPJStp4lIPF2L7GGbHOhpq0riwdSDurzFdchsyaOkmJ3ioXEj-mh02ZHJFtczuUW
vNqoxTiOqmk0Ofgbxl8NY2mBqXajUta7__KJ3tuYlWRapM5MsnyGTHQmbDUTDJ7F7RECs17fzwpQ7GmjOXIp1sM_cHKnoheVRi_3x6GKQKZcQwVTz1kFxvKv
wanWgLQj8s9eeTpkyvo2Ecth3VLeLYRwlvRauHqBMDUZk-Vj1Vaz0XfPZ2p5F1NSjU0COQvLAlyX-NAJ0Sdq6LHQCszJseTtGKXFntOj628-56CsFGo2Qler
I5z9Q84mm6OshW-H7nd71yUuTQnB9CcctnZm_3v-HuxoMVk2w78SpLfDmt-3L_4d9xqcf9Wu1UN-i1VXwKgjSpx4KYg3mPnBZi7HHvLF3_EyiS1FH0Yf2Ax1
DGVxM1h69UPN94z5rpu9tg96_qWM0A6Y1y_7yOUiyjpNJMDmqW_8dOzkoyHdxghYWQ_IiU0XQgHPb-bL0g9Tz2BAFGe4-K7wxol-XEAcQ2MBZIWBKHcrUHzw
UcEAcUVJSx2V28H9QImoi6BaLGwP7IvF6eUEZ8_0xYszhN90L1MPWA32V2E5PAvVOJ8-HpNtlfyNaXkp_gDLcJOFpLFUpJ6-W_167GIKPNeImAsngISpWVSL
kIa3ed3ZYz7Q66kiCTRwM0HZi1xpcnTZTOeHLK5HYYTzg9sA_N6Sl-bqcUcJSGa7oCHjaRBaKG2l1-m0f_IaUTYP6nh2bHvAsJVNrP7gTNnWxn4eQkrzoUfn
IRavMiNn7etFhqjh0r3QsKWqZ6i3P7rL_MYbcpgyAf15AfIltBZlx-pKnIBkTj0pXhjKHrcjWnKjlrGdSlR0sC1cGXcFK-Y0M-IUuT3A04L582Y_HB_tHRQk
4nv4yz_l0ZIydqikxnsNbct_ZG64Y95MuVBqNfLPJh7CPyJnQD49r_3734-MTKTLMwv8IiNx84XngeRlEKMjOpjHSHlPpZKie36tZgnIhL74Il5oYUzoH9Dm
mD1EgLvQfYxlMx2K-xnGC43PKwEqgCshs78igvGU1q7oqirS7jmFJAyCnQindA0FNnaZi5dTiwZLv-fbwGnkt4pTTzTQcNcwBsJkxjsY04ZMD-S3UfL5ZE5L
s5W5gnWmAW2wqShE12Htm-zBv8tmwM3mP8mXTRW0vFRQvYhW71WeZ04OG6W1P2biIL2sjXozboFhlxHQisasmFQOszI36snNT12y4ErzBD6BKWGWbLSrv8vM
0uBwcK1_vNdhkGL2xlzXzvWa_ZA46fKnnFgRIQKbzMnyPu27FdHcD9emGDoEOj3OcqUww0osw324LGaGCa1LctMugrZb7nIO7Zsi3dKlj3nVPjAh8sJgluDp
y7NPSeqn2W2_5b8QA4qTqBV-H-AphdTQFVPEfx6NojHnAj7chtIJmyhGHkmYGGMexKI-ApGW4w7uMJUFukx_J4KfSfIY1VJOv0Wov9Q7aF9jttgdsz_m5W4z
DnNg5wEjqThe6oAIea6A3qJbSGkkW5CaJHs33PHTweBuuB4UHVSgXUIWhpDdfq97nwCS5U-GbW0HjepCtvvYjOrOH1C5d1r4U17m_wDcFlcprDENj3665Zbm
H7LQXtzzMcYVIoF-rzViBwyAAK9AUNFldcD7p24uBy6mdZRNXDThEYMB-PB4shIj2yC0brwwjm0P4LazXBwluFHSSSUDqNX1ik25kdhc1hxU7MaIqhXbxWvV
aP4iK1X9yR5kD7T5c_5Pxgjjt24UZK_qC5-I_IYKUPF01gLNBnu0Ru4wfavVe5YCq7vzZAeN_oolb4ZdefN7XK7wcwuL7NypWZMGFSI4Lmpc4MTYzCx7L1X3
ZBFpmgTsUzp9oa1HfXTtttAQU18Q0Ju2peDLsEgAXB-3nrcrVN7QDpbu8qXj78ZXO8zQRYVDyUZU8bXLC2MKvLTSPyZPQwqV25PwPy2xI7NpWibk7Z5k_rEK
sqDv0xitEOGvPUoCf2gAuhLsWV15IcymYzm5Tl_QDmbypA-bVJsjpF2RpkQxP2SMj053j41I7fUTaMhrGttOezaB3f3ZRhfDTQ6HsVVPQPWRiOVr_eoy3aGJ
zS5XYuZbL3-DiVkytkliI4UFPpQd4bNTFywplJvptl2AJ0pOsE9F9qTdncxApjKY0yLqifRi6K5Pi7izozEs_Inx-75pOfmbBildd1M8JfVHeAC_pSd1ExKN
ZUHQIp9Aj-QWj3KKRROuKlRrqBWNDQv1cY4QOeYNg-XSExhA5A_IreI9Xpp1DCTEkW-aXWwVx_PaJY6YrU9uZGpwhh5xVI-7x7BimRhQlJg9WpnKb7wjtHq3
__mvBIP55QpzO1PfE_taAJd2l_C0tYwI8mFK4rqD6XJ9WyDVvT-M4MRai6zZoN6dd3eWSzp7syK1-hI4Y8R4qmV6-dm_sO0TWJivIBfibYViOvWQjU-ZODr9
ZdAHJCuW3jFkq7lxsYNT2KDeEWTRCnf2TCucgR-UtYDSGKp7CUb4BhSvk--JXb4hGlgiMhfLpCCDdwbPEhgxtenbvYcL0ruPT78C1WZpYACwANPoK6_6RYn6
34SvUDHrYkFjaFZH2K1svcM8NLNEFNNoADFLf_Y1DAfzt92UwOCxDL627NMdNRV_-IHfBo01zX3cuY2Ha46fnL5_SjyGNtb631XmNVYAtVOx7hn87d0vNPOq
nNzwOtaOvr-fNxQxM8Fi7TFQKjH1I4ulijQkwHN6gfYFXcuu9AazqNAxN7oziCmAFcxyzV0bzJK9jFeCUd3YIfyThJ_BGOsB9iGOepdRSJsgMbyoMVTEiQXF
OGU2f1EFwBnrRZWOrRjDwCk8vdOLv-TEQch88URkgEAvZralEiSsvUJI8QQdAyQQtRFLhydHpmVymDJjwLTpwpTT3Q7E8Np_sbwEVprtKTyK95sFPEH4ixHU
aL6Emtt8W--oEdbjavieDUP1zJAnIOVTie1OQdB4dYzn-tmwXeoCh89qSU7OUuDy-IbUbD5GZfBKGomqjbbxQIPSU-CL-1O6zu-dNTcPNdBObnTmtxvFErmL
C8GDvgKWsTvjJs9O5U6KEYv9a5uEFBtaw0Dhcvzz1uQnWKjq2uASZDUzGbOvsARPsHPKFEZ90bx5Bj0Ha3gdwtEx-YKukPynoN4Cyr88IJFk05Rri6818lVM
Rm1_r3xM3wclmfNnOyirTcpEJ6ZFMiDAjaYbFPB8nEjACImSnG7E_E2H9Tg68kWWa9DdfOtWQNTLkddIw2zqwUgBM0dewhBAltfS5BbSNxOIb9Bp7iOzkXXb
3s5imCjA97l00UGYOrU_Wp7EQarjWVMKrzdDATUMBxlxeyPX4JetwO-wxQB7Rn7QcO4Tt5TpCtU4j5OanrwEyQ7J_wtkFDGhLs4WB85D5TBxF-szk-iKFa37
9qsE__JkYIaZ89clCnTRF1wpw2-ciZm10Ofmon0loM7Qb1GCUGZ931_F8VNQpCWY7klSeeTtDSfvc1KKjcjqi300x8Mfv2W7qpOU-ScBg-HoHRwCxzqFJZDZ
j_OGcpm5ynKP8F7jXurbYBo365a-0Q5b3W2kbeGtOFag4UneKuLtqBv1nmPce0XrhtSq-J8UB6UFelolWRlfY7qZ-rRmAXtXMuLai2CEeqgIxyE17NdGuUvv
Ew0CEb2Uf17LTkBZ3Pb-Nf87REuFUvCMV1Tjgx0Pwz1EDyvGIkceYPbo2fj7tFbtX2dIf2ES-y0UggeITwcEJPPKr1spGZCKqYOTA4i2w3eqwCh-KMKDRT21
0Cw5c7DXqQbesAuswDaVTemc2bSthJekBsNvLjY32VkKG2GpUVky4sOmmOyJ5Yd-k_royzv4qbcpgdg_EQVQnUBWWqcGVJW6NP9F4i02x7zbkBmAEW81vBFi
PeaoMMzL2S3_KuhyIHLvjmkaJhebEQGc0F0UTfd9JGQs_OeoP7ipsRu6MjhlAXArMN87ddSRVQSjMWfXFtcbzcwI78jKj-hiv26l_WuDoJwo-hZwOIKwePS3
maEgb31USjl0ap9Xz4UVJON4Rlsgk25LCIZxl4aVdT85ljVnue0idvs5BGiPPRO6sS4bGkeu2fUXdUYxEHmM1utecXnzngaoRBXsMFnuxaQs5e9rvRHP-ZgY
oXdib1evWH4qLJvZKufFw73A8NjoTf6McHUn0qLKECihbNGVvTXotENgeDGu5zIYKh4RLUc10I4H1bE2rBdiFSS3SZSyJEGMmHRKZpRg95VE9-thsOj1sMT2
b7EAWzyFdSk0Eu1LD7e7SFyx4k0cE7b4WzjGPA3KoOxS0I-yryw54BYfSBe53W6I5E_UmlMdelL-E0zlEXBSdEbkt9HGwCSAY_y1
}

sprite $Pirate_100 [100x100/16z] {
jTdNOjfQ4uRXR_K-x_rVxL-s118oP6FiF2Tf8eEciP3r6MVMlFwk253rTqs0vVNRAktnHh2eN-KdhEDFRFAlLu3yyCTVBafX4xJf_7gG3fmh43cqNmmn0M14
5nhyTf06a3Iv277-LhhANWXlFEYIykzqLzn3N8DC9qd1099-n1aGzzztxeOsRluyo7X8U9niwkCLH7sk0aidBlNHihikBtFwL03mEed3h2SzM43NfnPGT72p
1kTYcLadRWBnbpBbbcdJsgKnFisM1mWwz1hZBNg-NjdrYNvzfKdkDllsPOhAfzFdT8XBDxbQ_9BMyAE2kxg2bCQUcHYRdrbg_U7gfU_AHy7TQicYGdCmfGbe
r3JBB0zjtd-mHCgG4YsE24Gt02rwb3VTjU_lb7PwNu7PWn-OQxIs6Yi5l78DKmS3tBVxrcddOgUxH9KyZ20DAzPAZvSUcP_jmbqOL6Fv2itb3iKzk_MgjoLW
w56Ss1mk1ZzVDEfwSwUyNWvv6OarnWJmBn9i_XkPIdeGL_UHNQTRUj7l5juUZQgpkePt1GE0bOb-ZQZT1nzOpgup6qogpA09GB9gIMLIdhpqlSqrlfRKN5b1
KkrjzDM6tAnIiFYqvx4QjZyvFLUVj62VMzHaNg6PbzmSRbhMLMHdPZ1Uj-tIXIjX3mOsjjQPHdp--iFICzxUtTAkHZsJEGmzuTRB8wnFjVUn3DOQBKUd5nP_
FjQF5pSOkm76sMf9JpZg19W6-TNvEJmBy4AFkigurNjRkOD_aSfhx3JvatMDCeSdhKmSh1UVuFrIMEFV3A-JI2mM2SZep-zYwYmRTwiQqplldG-v3KwI3dDg
rJho5AIdNpIMqo4iDgFaOWp5-c8GPj0k4pAUE6l0zCXtWEbqgEpy5Z6xLsDmEi6i8QjjULoXFHkSheCRV-foFs6cODmDj-q1LosIUjSWwYGlhllo_dAdOiD_
pUjAvrlTFpWIsPFwT0I1DZ7dqezhdYHxIAwi5Xxhj6_3o5bsDZHd9BIfnFWozzszgAUr86KBackjIAv3aNnRh4NZp5mchEw96kHB34iwyPoqnjmpwxrNDhgJ
wsmqE6cUNipt8SUwF49eJYVk7jd5rYHN_3bDSU_gda933IPtPfuI26gKXmMrgXvCJXLopXt1E-2IhVlZAsA7nM7MgTNbm9q7RyIbiywctYjZlPISKp60C6z3
uvo8jw9rThxYrMcFnNKZnzvTlunUtYjprYjzFvjq0DCzOcJJAChW7glRWdLRTOuzwdaD-JmvSJBEbjItAvCccobd51q0yBrPMtcDonjVeq_ZxE6HHcb0KGIf
aXiCWAB9-fByvYrPihXMMG1KxmfFhDj7PLv0RLXsoWp9Y0FyraCGlougNsPPnU9Yes1pl8ZHWAPqrApJbI0kYExfXjiNngnpDcvkXK-D1oQfqBntAckDY2zJ
Y-acX0LJxRfRZpPAtj9OtFZzRORoDKQaIwrASZrABh1nWAa1u_aH5H_ft0M_nmeyaXHkNnl2Z5AiVG2m0a06sgipbtM0jR_lADjYQN4oYoHt_by2-C3vfHR-
VERgaW5GDFQILWxx-uTwVgra78RJC_vyLkfxNnG0cfnnOrvZkpnfDs380PVr_I9RqTq37YyqgPoV818aWtXaYdow8kcr0PI7uyajWr632R2o95cMxBWsWidj
0RBN7qsE11Y0KmCWEAOKevTkCI9CRSA-IjvxRZc0V5h5TKkWgP2rANCONbA_7yCSE9LtOwW3xPIj49YJgR4taL-0hUtBLBkTSbdIWFfU35N0olscJ5uTktqI
k4LTlan9obDr_o9EKmGMHjGRuWIOlVS5K5m3_7uZawQP5jl1lEqZxuXk7oZqdjWcTsfRNHnuLV3gLbYrBO09IOgtvJddqFjYQRsLA6BUHxio4aofS1W5l1hg
d__OA64PO4yuZ6fSJDdqOxkgwFl676o2ZCtQVjCvgHF0z0cIOauDMFiqLkS7NvW137qWuewd7sMBiNXb1NsWs7qOOV0lcZxHvxugtbBrYR5bE1dl2Fh46iU2
UL7dmz17RYdsd5dEbPc3zvEJgOzOqQPpPxNMiik5awXFKBGPpnvQ-9ZgpmjYUuu3xudwlewxV6yTVl07-hv4ti-GksxE_VQ8BFFdYW-DhiPhmt-oi9QJczmu
PqNESrFOrVpvg2VcNWwhG5TYnCPc7h-Jmlf1a5K1YWIGbRanR-SJi0Ve-aIvj_u0B9pgqTcilVi-Z77-qNW282Skvld0xFLziwnbyR9HZcyg6SoTMqIVIK6l
nhraI3huf9zobIih-csTYw3VDtZGz1S49h0W0opz9Jb8EMkVlRzgCfpUzby
}

