sprite $PirateSkull2_200 [196x200/16z] {
xDdPOgky3WNW9Nd4jgJtVzj3cxtZJBGcc9pf_-uwio9HAGR_j_v1ZWZ_cIYKIXXGL5gE3lzXoEUcPiOOaEoRvCpq7zCQgTf5n91eVsb9Zl1lng68_PKnADiD
AS7XtuPYLUkKCOZLxcZs-7SWlwZTMJ2is5MFGVWiLzGUHGpBze8azyaUQlO2OvYprreaV08diLVqG8RF5eCNsn8FPUYA8vo7GhDj6SEITPzjgTZi9mN3glr2
paaHclt2xvyFsrh0R4xiLvKcbA4hRl8ui07Z-zAWPLuAAcf3DDAK25qXJ974XbM7NxXgUqZyM1jr9HBXDMAErVQg3iTGjlsqbEIy8ronSowNPc_HZ2EyxBZm
QlUaNQazA8vtD5NZZnIXS9yWlwjz0n-YwRIXrYc-EBKXodtKdLgAQ3lapP-fLJStAxKT8lQYQczaGBDEs-AP0M9ArMuezGmdpWelzbO6PrSBuuQlBnPSjLqg
OOUaja_27ylM9axr-L8MsqS3XXNRIGX_a6pTWoJzXkwVsaSZ7LXHXxTkhhqmzyBps5rihp8MGMqtXnjHp9JmXFJn6gZPAI6IsduI21s5rl32OirVDoSEkLet
St_AzXujgyouy0Kl12kzKkzJZvzmjKDqOQnyotWbMUb_vAGGB7P0tspgrZWgHfJKZb9tIeHE0fl3QqvZimdKdHEX4-Mj33Q9-dCYT0s0yo5uXmiNGgsHm7fg
21QRcS7hzMq5g5mNacgpg3irWgL-6XblEaW1RzEaKoDOk6OejqCd0S5c4SQ3P3E5Fsk45WQS0xAQQQ6PTGXunBCpW68k7a1G9O1JTdqZdg3XsM8JHNJDB9rG
ReTdr6mUzNVBgk9BA4MqdV0gTLvjcgQHRZ9ahDXaoOGm9KL5TqetLO-a8jBm9UHCbmpB9LJMRwUi6YHsaEHOfNgiA4RHXsQLW0jQkMBlyzZYr0x93-SOYZlL
RE4fBzc2RScEAEWesOe0wg4U3soM8zDjMxO3Mh_U89VF1A-4RnJriPNBkn4SVhHC-NyNhAkHYKAMftB5kVTpnp8X1Ed0W8q7xhfJG_XUXar2FUVK21stmwCd
3mJr9qJeM8vcQ0CBPvWKONu8TGDBYpWWwAm8ymUsvX3LjkY5bAewDSA9RwtrekQSLZanCttXbK-fwQm8yqEevBWA0RznCRVJdl1oiNVLm7Y9t3Twob7rm7IU
ldPeYOpEXrMixKBkdrgN48A_1E8e1mwxPuRGcXWNFgP5H4RQJbgA15v6DjNzNBDnsY8184v9J6sdoiW7LgGP6w0idW5sIprqgBQbC0xmEXB04IZKfhQNgigo
SWniXj20OsZvjGA4a9hillQSaYDc0W5m0QkoqMQ7-VPZ0DungMILOeoUY9Y9N5uLNPcr03Xx8XupK9ID5e8Rcb2j_gkzCz5o75V1C22qI_3-Jpip7KV7ZcAx
bDkbn3ddVhDshVw3X063ahDjTmOo_n5JahqsbDn_p2Fy4kXbf_qKVVbXlPGOw3_kSnBMbVyuZIIuUvLePbjb8R3r-E9J21OH-oxzSshNCvhDr5a1mKEFLHm1
_cyTWNPZ2CaC4zW41E6WCoYxFUi7qIEgT8P8RHzC79rfPd0daKQ7F-lfngtRSpVN98aHPc92LPNdTBC6UlLcNrtVwoK443p1V3X487cwqUtG5MfgtXZDcKr9
i97XZPW70T0urw21RuwX9AQkZQF17z0WoU2uN0s0H0HFMFc08UB9BZxRqk67LfSAxoErVE553MgEHFGjTVCX9Y3cG2-EQrGyrw0MtWXb6HeduoxLkP26Lhm9
msOulyJG9PtpMUyFwIKp21nHth-dpMYsddLaIsFIzsl0eaE6yFg8FIcWJD0msWDhNYa-vvFSvEqQOCWGNdlyaOAH-yDlnxDEVpQ4-Qc33JcVQEmXpRCqP7nf
YAmboSIkLEsfUAP12NuJEcnXwGCvuQfQapQar99JbPUxkKarJB33YGYxndaK2s7KCUoPXZfDWqOybY24_p7Ug1PEJS_mYuJpSfpTNDEY0UBVQe3KcNo8SSyl
oHpCo7BJOEGlDQ3yhWRM9wednATgUOQc0PAEu4zDR-7tiBfFJYdbWqkoEWATlMm5VpMH6wCIjiun79guowVHleLV9EiO6LSDdI5Ir1tiMPIPu1CQ_AgXQxgF
zgoFguVAxsT8JeSGizMmLHwnl33OwgJjhRb-INvkQBQRJz1k_VKiHShJag26i4dxEnJHsBinyhhiiTCiXoLRaoVbsdOl8cNPsw68ehpyZztO9sslF--R015T
qntWrmbxQu5bHmEb-xGM8cz2R7F_tyHCEqUSfJz87rdE5w4kT1hM1wkbE6lhzXDULRD7w34sLNq6Pi19d-WC8S4LEKmJN63eeLX5Tu4v69ThhGzUFx_KHehZ
FZl2J93l-1oHNnYuvY8y-jnB2Du2CuwFrtiWwMi49EDcm2cYl6eQZqBgufZARWTUvl2J6RZYfFebZVVk6v8koCjhfupziO4fgvkaWSSrkEMQmvEppkQf9zBj
1JjsaeOqhY5q6boJW4yI4lHWLi4PZoJ6DMHLJPs6kioG6mHNJsOs48rphanojbbLpP068L4bh0yQuj80YXpFfdzibVRHUHfekShTfgVgRRvz5ZXx26iePmm1
s1mC9z4Ulnik9vYdORcql6iFkYyPsVH0rCKhYpquKgAwFUSh0QPfSFV_2ZbzGh15UjkeeYLK1g2SPtPKMiNM8ypJK6bnK0LHskvTGG10lnp7N5SDkQrl8oVd
33O9ChCh9RTbcbJZlH9ORM-7FfcjxNybCRYJBdKihTbr8hdjG8oXdLgJRkj3dY_9TRU9UmL1LW6FvS_cS1DCXRl81gDg0XOjP7m83Zl1QyZH23SD8YK4HxHt
CbgbYOz9CmBMlifb70AWnPC1Yu9XU-ispdiYyZwgQchVYLncFuDllkQ54efPBrjM3GPz4jrGWZ4SayozAQnXWkaMqrWoRZOQegbw3i4qvFuQsU42H5wBDAcL
bmp_927Dxdp8pVsbGJEqEC9wxnpHm3YOWMauRMl83ZPIXKrMJQ9ILJNJG0u-MOEQre1eXZMaJH8jPc3qUnfvjNGUg2fYIBBDp_mYmRQWz2EbZRg-JBoKZvs8
UDZ7IfzZSgcrMW3SAwY9lCCCl1QvMvHqzaYdw0gPFqh3JOhXv0qpsvGReZNQ_0upyDPxfwvmptpSiwl5Y3BGJQwzVoXQsfvS6pkRJTNG7EN3-iMiQe7nG4D8
j_ZYjammLEdU38AsQol1MpG8BvkZOHR_8oeEW8EdJeCO-QE1LMitjICf-22YAm6dQrX3Ch_rXL4NAXfHhVYe8RYR4ukhvpVvyEIKkV335g3jP5lLEyOkXjbg
p5Xk7ylR_Sz9XcP59pwRSmUJ-BnK2fmB6wEPcuMeys4K7bJKwJRedyrLsX-pbxqwNxY9lgdY_USeKYoyYVeW8ke8zMQnYb3s72Vn3O9tm0aVdniKmgG3kDi-
QXNk0f-3H5FNNrK81aG4nA9Q4EB7DV0zNYsF9TwiFr3mNb8Z-RW6bFljMHuiGQBdc2LWfnQ5rmzhgDG_3Om_DRxv9VVR37YPJwwb5XHttMDEJn34iWHKII-Y
GRcFgPNFFApmOhO4JY-ZeM8_jv_XH4J0vMkj7K-LvyyGv2SH_bX4kHyWdadEK-Kttw9T7tKA7ntu8kQ-2rpfKkLF4H-oBFyeGlOa10pQ4nry45exi3fJY0NA
sf4ZSTMU43LSmH0go_IkYtLzYaF6nfHgINy8HBJ8wiXBbyJds2wO6lXnkaHAoSvvxng-7WJc7Zv9xBkk486pTameGqvjiQp9ac7cgiDu-2YxiP6K_z1n6Dx7
hDDh6RvV1CFtYp3mUIZ_bOeCbu1y4Xr6hcQ61hfHQnJxg0Yk1FewO0HFjRyxN4n5_lcelTJVf2y7dosfoayTqHwk20OvyK0a5pS3cX0T0OPo-7PNiQzQNWtV
tYPe9tWjPkU6ME5oK5nVSOhIZVTsAocIImmNn6yQ8idLVhOtRpV7LS7oSEIgpR8zxz3fIe3BWlBupiNeBD7sSuq4ryLfG_nfqXVWkkI3yngfz2M_2rDqfJOL
5BN3mcNfSsn9pBpJ5EFXqWGzGQH9k3PL3qbev1ia0DMJyJwiJSBrHKXA-msU50ry0-W2xmmf6_W-UX4CNqWvEHBbIy2i7H6-35Er8-2tIP2JOzE_X3ozMNW-
SNw8D1zRJXA6RpH5HVXEC7ShwRj5LFnU4L7M0U-lXKBjYWHV2RjSss7yNmmI8UpnV_u5
}

sprite $PirateSkull2_100 [100x102/16z] {
pTW7SlEw3ePXWBtYtVzkxubDDrd9BwNCt6TQ-ZTW1IF_FuBAcvI2oY_nkHj1taIWb_ZZ78tD0BBio5oCyfEOK8qhbHtApKZVYz4ykPcoQ_BGl9pbYl5Wiiju
DjAvXCOhBpiy6vQF9rIskknel9bHZj32ZYflAdjca7-AarrMWigTYyNuH5NvaZPsMBq6cxKFtOoB6YexBCeNeh77YtJOdQHnjfJAFX5nNFGSDQH-ZvREhkbb
bnlii_l14UGgtfT1OPybsH6CJ-HRaKsMnoVAPwgyINogEVaGMfGRRqb4l4-TJpKzD1KFtOiK9tSjYPzyRRo6TFwfXYeFsYjm9gHpH9GGl8Xeo44cd0hf7E82
K4KDqCeHLPR2CUADwLGJL2aSuMK97AEYNcGqKISwZvQnD8vOYn4JYRrcuv-cFAZn3zQjULT65l5E91KHJJcF0oDrTBI6N6JBSf7eGVxZ-4gH5-b0XfjWjQcu
0X15nFE59kVsUNjVuLN4sO6zSJp4YTZRXAOZ4ST3gijiv3GFH1mDMSOOhTQQOep1wOUOspmOiMI-qAxDiweB_yavnn22Ln6N1rlrz7MEzQZgOsd3Tegh8Pxf
6NJmnchqiKu-OzOrlAHw-LgoJK1A-t_VvcWrXU1ZJ57IgNvKAtSrviwhENh9CSOGKsvZ6XTPvkDUFi9tBgOhF5YlENYzFXficxmAwLwEyXKWH6wiXK_wbpxv
46LYrSiPceR9uAf7UJ8s3vi2O1gIdAUw0bHUyA6sEKlODdJdUHXPFtdOn4ttP_8jcaA8iXLtTd83LBub0l6JTsQG9-FR6GhGzil0RIuua--fwqxUk_dpvdtw
tGp_NaZPzWE-lHQs-7nci8YRqx-RJO1QSkdsoUqTJ8vnR48AW7FU7MXqeXmIDkTS1MYYAsmZo1D7FZpdowWv9bj_IlVxAYTF-j4w1k-cYeXgMv_P_dyYCbsE
wRnhruouokF6mki0U3acirZZ9egeYkW4J0TNrjph-pZBGJfPHhJ7gDUXeWLeae7PSf0h3I7cTcv7kivYXQle6rYl1fX8xq6MK2OtGqxmkTJ-7yl6ko8QTpkQ
BEUvefLtfeFyj3uwLoQBStBO82Lsf0vwEm6cRzijN-gPZBQRKUer8m9DwtQal4Kvh98ZODnD815M7S66J-DbD_fkO7ec8ybWH6ww171I0QzZUkcRbsbOxTPn
bI6UwLO1q4HI4WyGolCupIWhmhAJCmfKILuACsAJ6HzdlJV0F82D_BXzlPpWk_Utfi17YUxbqEo93pxtaajlKKHz1vASqPWozdv93KWDe1KMctoOSie4vw3j
dvdgUYiXiv7a521AmtRli2OEc8qDbJC2K2H1gjM_FUooIEhT-sOiynljRmQ6gAtj5LuRnZIa9IasQWh-FwaCmFHinXgi3zhftMlIbJ4xEePex43FgThZKZoR
WGjyA0RKIb-59KolCvK6Y-NljRrqdTnCWs40DLFZROB3iFLUEKd3AgG6sxq_N0SlFv9nCbS8Mo5H7H3aHo9LF1SbyQfwy1L8Fwq3BucBM7bcRj83GFvnnb0f
gqTy2GaLal7piVBhiZ20heEx6e5vpPQV6S08ejs07kgOp3bRIOrbjYO_4_XWDMYQWCrsPJmK-Q76Cd8kx5BvgSw_gFnOusjJVe7FWnrcN6Jv7QuQ6osjA9NV
eddoP0PTgKL-Yol5nvTkiFrw6Mv0LT_kRKVaGqrHVeyQa5NpdDsjJq5-LmIOyNNN5FbTbNjAd5nb-MMJ2vjswpgB_3PlF4pdAVBxV0sH9OYe_97CLVVoLxHp
PN-NCRWQAdycsMfAv0-vzIRuKswkeVfJeKwcax-cSjp_
}

