sprite $PirateSkull_200 [200x187/16z] {
x5TLjkim47k3nfdiVxVl17qAkOqlblHTa2Amy-_vySORRxpn1W2BnjmGLGWUIm9oICM62xYLg8yY1hIO3_lm6l3kDP1c7sx24z-pAHYA3yVW2UzLX2GREb3b
7YsXQ3xqmQlUcISWwOe8TpVxs2ABZ7UqJzNF59GKX8c8RnR6QoAuZsxNKruvCCAuN1Ah7yfNbZyt1OAjR6p92KpgjFIK_ezF55HRYUJijXuAADc7JjWVAf4r
KKL3tSO7evrSH58CGKU46BFvtUqm9LzABHppGW8eBaojvY04S48E033KtPxG7nHZDQC8Ic8uqUOr2WBifJ7kcM8A_KHO1B_GxvbBLG1P_ns3JVv4la67zlhZ
iPSI5HyZ-Tc2v-rlWN0xHgQ-4ZIrW4WioeG8LzoyWa9zHEfCHE5JrIZpV_99NKOh5DihYCHsVtUlMPl2apKuHUMkgVdAjHFBPGRKngh0DiZPV1sid8Ag2DE9
9y1bfoGz8KdDIEwr17BhPAkk5uMLOR9HGCrHcSQwz_NTEWOuVk5D84n_ngSvCrrh8iK7ozegiGiGkzvsFPuhdvR5bxdhKK9sBeEjJJ-baW92Hz6-52sOVY2h
TTyAO8oaoqarh1MZ1UaGu7gsZBkUgkksv3KG72lv-CKCZOdQLyvX25U5rCFFLNtKJMt9BHrImgD-RZo2_QVbEjISnM5WHkv5olk_xNqu9ig2IGm_foj_PSDO
VIHld5V0l9Dad8ew1G-4-j48O2P2C5GRLUFMHR538E5SAWnQVayffJbMrdYXkV1c86oc7vUtnrBGrgrwWn_k4Tumr3Lk1p9lMM75JLXw7utV9HXy2TYYGVQc
viVovIoYBa8FuqrFmmh5uR0Gg5WJyYbj0200E3gUhHISSv64XqaUcuPKokYiiJmHLn-dkTStriTSIgbDIYavEhifWFq0Y9lNPtiwu47vLVM1bEIePd1kcWHX
Vsg3Z7KnvrAxCCjdnnkS8Ks8WoI2QI1UkYLIoRHIpIlfbB2tHCrHe5yeREEmYD25o2ogIKKKJ0u6MaHln3zELHbFSNYO-dfjjAEEhEdkGunejFgtyKYkieag
XY-7B0KIy70Icg6QLvOLTGILe87zdx5yJ1YurVnx5n5pkYaAG6hdJyb3yzqe2Tv7poXRr_hXV3cfQ-qi4OPBqsyDgoVaKLZmzyvzWjPtZgzxkch48xyYKM3g
UJiDaWVJxJJtwlUoZxtsFFjHoRqYb9NO0kpkw4bzvbQ16xTJfsCAfVRMnFp2aH_8WwFtwdgtwwHRr_MShjLVGXNJWbA1uNt-GDOlVBlGk9-I4rQiWQWyVVjv
qUPr8dbS5_ea8vG7kkGWMZQb5muhpsn5Z_xsvA42ur8R-nohPDuTrODHdwubnjZynGwmPjpkuvbvfHfT_KS7iUszISIqyi3pu9MjQ0bwSmfXuHAe4TWx1vd5
eKqtkITZiHuPUSSZQbwwMn1g7nDIackbYVOX6UcP0Uxvg68G2defQMw7Gxw-5ayeNQjvjNhtgC_mS4SPo4ZN4MouEuSe0Lz3l9G9LHriZ8X5EWhSeV-cILzd
BQ3MOgIKSqunACl-K_3Y1BSnAvtW9bk0GtXMGj4ARPHXu6l48GATU6mdweQciZfVfKsKU5uWfAOQVNoRyJr57iE0GjYABC8bpKm3JFv7Ob7y4bVjWrWVt_Cz
Dal2G17kasaHvbfoZA6jPgZG9TvwFaIwdhl3iw9vyt3Y5byh2vdsyzB4ykwsaxSw3Bo5xcKwKLg9NNwCpNowI3JOA6r0WvEhgnD41-1-JaxeX7SaB0XSApws
MplMXH0ZFnlSVVvgH84pro6C6GCLCsbM_VsCCFLpLzd4mRWT7elKvEZch1WkuGZT1jsh90lFO_dBCDh29PZh8Ex7qMA2V-PU-HwA_wECpg3TBqx-HH_scR6P
v7wBW1Y2095n8QQKKbuaBHAyeTssoHT5slCujEbk_g7SjSfSXG0YwrAfSg1EuLhIvtu6J0XsZCLSmc7wO0P5lAfr9F4GWukvydD2sdA0CrYN7jA8igTBE51N
HvTAMlrEuW3PKCull2RVx0g-rFro4F4L78_Gtn6nPsiS00cZfhJAO1S_v_IMNAeCiMHFMAWhBXwRaxs4WshF84ZI4uIh4pXW8syze2N4lpCdBB9uVofrKqbA
yGRmLTZJCOvpa_HgMf6MIFVQHZZ6g-nIKpXSP21ZZQ66Xgo-eWuDA71R61tZ43ex9cn3_Gu4DiknVy2eAgIn7JysxqBAfPIK-jfV_gpnETdbmwh7F-3GaFLo
3fkpKRCvYBicyUTYDoQ7X2wycxISKkPFfGJMqIhgLShToHi8GZPQpFxPKyqTnRj5a6nneG8KqHzKAVMzcOPwbS225zqDDC5-plXyBFnnCXJvqb5fefRWmc3F
KjuxlCJN-bhTkgaD0MWp_wghfUf-f6HNZbiSuzp0tAY-NmpaKfM3XL6IYpWK27keBrlRWgKELvr9yZOev6Eo5pPMhidHVigY3v4DTRWmQkGgmQkc9SbWHRRZ
3LRNR0w9_6rj5l15-jQDiZ9RcX8QCLGuoYn_1J8uQepVs_Qm-JcIdhIG9CNluJR9kloe-sBfxqU3_FPJ9lX4ZKB2OOV4L0r3kZ9vk8IU9AGVEcvvmU6p-gnw
K-sLvNFz2aFChyip2ODys4JtYMcBH1H-4j--19eSRy5B2Tu7xcviyH4DV0WnfLpu2mxyv8VikB-NFmbEju3MnGV5OOjrCRNjaPoYjuPml16gZwiw307j8EpX
hKF66COu4YYCubpevrEJ9-Y5kYtlavw9PLlffbspIoxMmKOLXLooj_WriyrV4ZVdik_lWhntajlvL6QHLiOH0Dl0jOm1YuvZAC9flvEaDgapUmxMDEbgD3pT
lE7r_iRoBX8uqKzIuZo448CpU81iN5UYZ5Dl6WjdJxlDLedGp5uRxwkNXoqmPchiOUURWBBZ1gd-uQTqquZ8E1VIMg26zcAaRC2HQFWEekJNuMAx97zYxcnV
WOnajoNcDOB1X9IRyvQw2E_CrKPyurKqwA5byOqs3YyMYSpk8xjNSMTs2YDUAmRO8YBobVj1CLgKVfFYRFaBWrhdCfPK9wOVYeCCxJZEy5xbZIKsJjV7GUlT
6Lxaq4pqjxnTm0CmBgHw_9ZOEC49A0wJg2gVtbp1rAv2YjfV0cHQeYfjHRAK-WuECS4zJmWxMohB3-ZEpQvQsWQx6j-ZIbYElUWRGWEwYZfzNNt8LqedO5HB
CrReYHMvkiTHl78SAOyzoj3FTguvY1LNfb58fcQtFyKZQytRzVXjgJkBHP8lbWWi1XM28s2ujmHccSOHy01F_SNs0KroqMz-S9G7IvlBkhyUftC_c53UxYab
6i8VTKObiwU4qHwSaAYTO9J3MAL3S5SNIe5SB9NhEfB4uw1K5yx1KZy6DQnJEEnpHZBUfMhSMCWueJjvLekt0_zf69XBJgsMbWqMGnJVXbLFuQ0fs0Nh-N2V
MNwdtDXw6LvUHqZUKWUuQv-bLduVqxoRLpmc_KDCBm2VbTk3FuVCP8kyY43wr8PhIYBhOyvjnEb7L7gUVJ7bdp07EwptCxavuiGzDIAN2ZFdyAaKDDgMFuSL
HKO16YVy8y_7XRf6jlhTh7JOayrw6sDYRNChAPLf6FrOBSyeK5pt99wuiUPbSs4GniSKpAj4VDuk_jKs-JdCJjHyvpOuE3bZZ0sTmfNeqhkluNPLumvGtJmG
pPIc4HJJ_Cr36LRymH8MCJQa-iyuEdTgoP-fJAOs8M6FNu_Z7yU7ZVNVr5A9y40WeFnKS24IrUFiDg2AL3uU1C26BPIQOvx5aG8lLkyN7Y7oTzNPZtfIxFpQ
hBHTgUm8S8MPZ-wemVpHYXYqk38bWPyLeONKa0uCGNijFeL32H6bpa1VjwPW_9jhuCPIpnRj2rUGchd34wLZ_14jbYgE-qM1vxLWS2VSXd9BXm0QKJgMXBzf
tzqFOBl4g_JZd51fSSjRzStXD_m85-OUrwIvHT2np9oOsixNLujULMy9rKRAsmlpj8jYHHcZ-HRTSNilP4wEi0Yv4DEBUH3EqM4TMzJPuUDrqSvMIUyvoTBv
lzAtO6kq7G-jDHuMRKXgVqCJwF-9Gp_W9mloNtlNeTou3iIuXNMB__zlNoIHiaJhxZ8bbjzCC2tkHYXMO67nKqS6pE9Nxe6UesKf-SFostc4wFetAfPFjo9j
7YVtTRlf1uCCjLNfOdjOge-tyu3MiE-rhj3owMPDGqR8i4vUFBJ3xcOWUGX7VmEFECrGIM0OaMTuqLJEjEeu1nCyB_TyOH58h23gE_hvNEgLqj2Sn5za0w5s
vY4mbFIAHplsfdroBGGeFlanVWIWfvqQ76m36AKsjIz8BQkdj-6PHpNSNvTXNxbjcW-i-LDOfVWRvi7dmVnh2JeKE6ktUUPnk28HDolBdcBBjFABr7vmVJKB
9JmEvFb0X4euOovW5e-pmmmE6jNMAkKDbzKfR8bobSh7HrAOCF7mlwxzSeM3nzCe_2nGDYKWsnIfmKBNXqpVNCEIyM4LdI7yBBfxmtmoxQCM-0CF_nuFpy-w
eeRXny5sDRv7nnSQdSVkuFE_sUVOQ_5dGS0Rm7eHKLKCPXhZz2FkKniLd2ev5oJ6BvGvi-yzBJ8Br-s51ohru9t18-UpPbzqS_JwMI5k6Du4rfVM5yUPXrMo
zMcTHylMuDXUZ83ZDEOE6gD52XoxDCqyrAYipwgRubNS-THzkh7yFXgTY56twgUSz95UPuzAiZo9HLifuZwFfYnNUPPlHUfxQ8ZYVfqx6zqpbRYTIwftJyCq
X4-mDzFevNhnjFkG29DExHd6D_OsyqIzadBU3VPNQyjquQ1qwnYqYzXCg9Udsky6j7ydKM9nnPLpnJzvscmwj7exyZVidL2SbwSANczbF6FqwTLtN5WTMciL
E_v7QUz6SU4nRkBvvJPLa2g4T-DafuyG033RSz-m3qqHUwPMl_iKibVWh87MEtY0pgCCwVulhNmzoD79UzdWxDVCuGx8owXFFZRljLxoi3uETFt0fYg9T1iF
FnqguxCzBcLZz7fsGtC8yRJFkWEh5Y97CoZk_QFQ5GzQQCAXuf03r9jvz5IlwEjiw0bwUn1-WTHVYsfXCGD6v2BwjBkXtSuZFxfcfhLlgs0XPUQsadCpAObn
0QUyVNqtC_TXi0uXJLhxsz55141vA4alGAmF_wOnjr-CeDCaUWDuvH7OdSYslix2PYvMJCKULwJSxA7k3_SYr9lZPXxKQx-o9uY-NYLSgCN21Hi2M-Pa9khT
lEKbPIk0ZKkkjL5EqycGutqyrgkfhjgKOU36bJDdgY6a1W4a0t1pOOGe4A2L44hCfUGQSvfKNxk71mvxETPjtCc1J3HdQWkFNCRo2YGjj0L2A0r2YGkJLeLG
PWlW7S0zs0jXdKq4epTNovORX9f209ru906eIRYPsTFTOn_2OvzDp9j4A-gAsFB2e8mZpn0N7ba0H9jArLQ6q2pjnkLkDoccQHdl4Wsp5bcu15I1iDbaGXK8
85wAAzQM-XRA_M6nysdX5e2UbgZT-Ulgd1IZDQsvcH90MRLQzSpPlEOc86Qx_yJp67phZJpguVRGF7FoX9gfUMCrKt-ug6aoqwICAcoxY2YFkjygD_5eB_O9
uBgjjnIr1BA4LcAi4dEs1980bUFUhrrpz4Rjtkt7YAAvJaUhLWDgHezRW2n8GeiXUjkYZKfAaG2QKbwOjpw6tu9ukRORbPD6e0qq1v0r88oZCTJkyEpiUTFB
BVL4t7j0VYta0Qx5hrhTemYIFmfaZ_AGvW_B2FiJAvEkFtlHWoVl0RGH__uggT6Uf2soD86V2WixYB4jhK5onwvsDcTNW1pXEh-lsT0s_29OOosKq4YZdl4s
v9xhWEKgL16wZOHZYam4brPYuMXTtxeFVNTj4LkZAsVc5wIc-8NkwPmBRniLxoUgTmBwjoYiUYOIgvoivUxMCaqYYXTkqo-htOHHpDoY6VUxDfV3gCxDJQML
74Tpu9E6nTZ5NuPmDrYxoVgXt5i2vdvowXExYYEn2-QDmlqOXallVPKj_lNPqgKTgLHyLatkxoJ3eaugy5SUIXlvtDDGBDvAupfCqw8w__svQz8gP2Qv53Rl
xoGhV5uvuZpSLayG25alPERxGN9bX0QkQYQdg58opm39HbdwXm7hwsu8SykHOsxQub71yV9HFVowNadmUG_3dduZ4MO1o6BuH0pxb2OupXj0X100cPvozEVr
yDcWS6BIQmlSz1dZXDdsilIFnQYtSIsH4FbfT_2stJ6YQUowQtpUJE8-5Tkxc_jaX_bWOBLl_BmsX8y7KF7phvl7f7CGsFy3c9fwxoTq2YATKkC-7e2Sli17
__jo1m64z-8Nl_Z5BtxnY_y
}

sprite $PirateSkull_100 [100x94/16z] {
xTY7UkEmhWJW0TX10lF-Rtk_IB8ZhvLDukIU_c-l8uWDDFuH_aSqRvBY_uMKiO8tFkjlvsYTV6BwcnKOBqNxfHHfpatuj37v82mBVafxyCrgIRHQy8d_i1Xf
GRhDfa0sld5VQxdph0jUbfrSjHQ152VNA4cmasHyvmKVa3eo_gAHKJKBa1UFkIgYSkJazOLI6ic63mtIjdyf8qO2a9fvXAzvF9hquDsy3bb_dUJjzW1fcG9I
brihAZX9YtVhCgIJaun-cQAtYB8o06r5y4piaqh4kOf_aDAvzeWX-9l6ku4BYUpx4djUIejrYsZuHELT-U0X2gGwoUZf72F1120NuEiXBhWm6Pgov1aalUAk
RFz0Cvw8fBJjxqcUNbV71NKkoGsGjkByHctxUS8ZIQMrtiUmwK76xDixDXv2S245fzG62BIJ2Jkz_VHZejMSZ5b4d8U6AuLSQWcv0ivoBt_X2oID8ADN7XOk
bU3C4p2LOCREsV0rKfqCtYHSocHsWTLoVv-98T_QdEyQhZcB9ucwEB0RdFWIpIg06cycBWcPGmixgVV5KRv-3eyYQ3m4BcL62fbSjFVV4K3mDNd6I2MuKroP
j3hrF6231Ys2Cn5z8tALiZWNT_cZ8P-jdkjqbZBal1BwyhWr3hqe_Y2TD_LwypKDxQTLgcGtULy2JZBM7AsMdDERosFvuubL65hMFcWhguX8VT_Tf2wwjQo2
JsXylC4R1qP7vYuyJc-rh5bLy2MJ6xlyemOhaE297KKKEO_vJWINniSPHaFlGEL9mOcasgT7SBSr3JMhG599Wfl-SKPXgBe2W-yo3fBQ31xY3M_SMf8ycc9N
FyuGfw5C0VfJXkwjRYnh9QdA6qsvj36Fd97pjFHP1WhPa4s1P0yPoMwDBiuqrpu6IVCjfdStVSyO7mrMWsmrw_5coYsXAQx88lt-ubP4arj6nHKnSWXqdpnb
akmoICuHWdUvvjC9laJASDvCRTmKN991hWH0ftFZJgwCuWadsfUbu_N6zXF98xZp-RnVQP-hd1kncUNKmKOJeCpoT1mDbHJa_c-rTECZnLs9qs_897s_hKXR
xuzJhBTXDdfDWfsky227x6KKLSqzU1SFkulFUs76gD3IvvezQwh6sCQdy2vcIzYKUsjRVTHIiaA35qr3vz9rs_dgFbAYkat-RaucPCNWWxMzlpWYr7YmSTdp
6fkGwNQoTaYRA_YkGPeu_n2zxLNiWtrdLyU7iHVdJ81eOuYqT2olRZPjSG8ZyP8rMy47vQhtwRHPIEuxUKTwsiG4e_DAotoIzsFiSISfzDdoEjs0KfyUVZIm
GcOKNkde5ncTv0gsFsz9qIJbd7GRm65Zc1ypgAJ50GbUQ5SPJKakKd5czBnY5DqZiwJQUprTyXsupAXNzKqOwLnFn-zIBVdee_BaBdZJZLSorFb46ndipwrq
Z9BhMB7g8BdcNC5FAQG6_rJcvNwOdISpxSTUN_ohI9BqASHJNFU8KgVxifR7cWLtslOOqyvdqvjLwPqFSZrg_3h9BLYH-2muV46bEDzLMSS2_8xzkjDuOGHJ
Iv0oWnilk9zFtw5xuPNF5ZbqpJ5wJhdMea3ZydrzViFz8cMBPp7t7xAK7ZPNLm1gCNfqalsLEf2gTkVDjFc-WvTwkmyEBJFvjpCaMBSCsVkukPQDBDLF7x-K
122F9g99-lhsUA0p591qdAdOfIDZANPP0KY1vY1Ty2tYz3A7uarJ7FpoHjPLVI_ZUrBStw-EKpBNyqeO_HYD5q9SyV3vahH9DfAh2zwaCNsP1VU8bq8CR-h0
JbRbAkGomnjHgPExZfTaCairTq_OcVKifVkIMoWFXXSPtH-UKhq3sOjWDta8nOioxzeHCXL3Jwr5jv-LSPpeHSka0yZxebG0wQYp7izHyJ8_IX0B0JhkQjhR
_ORAD-ad6RvV0xeBC0KtlKasaeRvqup9li9TqJd6Y3bwIIdbqfQFwIIBSgDucR7do34bJVVbYy4RZmWV6Dm8NZOuq79brTfAAQdfBEQjTZLfhRUcUsZy8AFJ
W2JkoLSV9ISPa06j6DAxxKrJ_2oZqVPNnXXZTgioeOPSPPRLXXl9wQJZTPNhw9A2q_Biq_hmPZPcNeqapHl9XTVb-xcZ5hGfrdBfQRJKEsFPo5Q3pedNwUdW
ISEZUQzj9flDLn40kImsPyCF62DdnKvICtSFZpKIDZgY6aFn0-gCsl9x_zZxTfKLx9hNHLRyY2xIPWMWWbJxiBNcg8ejfSuMZ88Vaa5wL4Z7Wm8WZqvwmi_L
85bdneEQaAgH9lWDENXldb9hIRQVh9GcsGM_8_bn-KN9ghLl9NLtikBNo2Jt1Q6rjoG2g96HyOka1UcZxwtKwcEHd8hVbOoRi7M_slm-hJQj293wd3tZtyV_
_1y
}

