sprite $WomanPirate_200 [200x200/16z] {
x9a7Okmg34KbH0T9-r_jB-QDmJ7XTJo_dFHaYYzgLnduUVxdV_xdVz1O7qkfjJApY33NKd9EmHhuHs2i3xcoVWuNH_Zc6XBhDy69tbM3BwBV0qS3xuQDh3-0
XJS2NHBzCHAy3IQA_Z0CRuBDeZ-1lCc8MAiGJj4x-nVkRxptALVH4GFFOz8YON9mvZFrpcT-dqBtebDgSWHV0wCUU7WOoZf1YaFuDeggg6Pu5iyJ4Nak0WqX
tluIMl3WIKoHky-mS8B79t8XbyeYUd1OnUp9D4dqVEEreYEYckn59iLSHVIE79_YSICzG7WCfrSa6JZ1Rt2Aujz1Hz8B4l7C9HEAVeMpkb4F29u1YufsgiVp
Bu6_ouxeWNjCne1q5IR9R5-oBjPFx4YxVNX6HjQ1YAlHBWuQnDhfLT7qvUqIFih8PcbvnPnrOsuXeLD7WGV8lLGhlQuIvmObG8VwBNfLbCS6ID6JX6UVhJe5
Np6Sz3Zr_NVFHACX0Q09eRBOBEZ8F8i0D0bMV6Y0f5TAINVRYrqGm1pdpbeHKAz40F3FR219vOiGHcWuQR-Oue1KCo2hUg39NcuV6I3-Ni19LrIWenkngeMW
8wtRqXCR24fFYOOfkWR11a0oATmbbsvC4koazep09eDrJKlyqCxRThlRrmxPFGYnPPMeQ1uzxnft22ZnQ6qoCLYyVPEYLucNopAtfWuJnCyCLkdVRW7Fh2hc
MlHh8Y1poONHo4n7sjruepROV5CqIdmL0RRKGTCg8NOvmyDOs8JHXepHa5M1n_FsH6GCkFRZS03OYp_ijbKUXs9PBqdXiYhIsPWY3ysCzZPUgvVdmwfBsjf1
iOggiZU8GGvBTcZ2D4m_sTYmy1KEnlPZqZNKyz4rCIercW--80yDoy0Ed5xAqNyzgqOGNV881nIbf33SBEnq9hLdrQmuv6F9MqJ7gbA28-Yu8jhf1R8fiP3q
G71I7DA_cS41nmUoqRTLNSxmohu9aY-nZtgbkYno5v1gpO7QvSTQlCMRHuv39umRPeUCMMy_7lXDcmpZ4epFCiO6NURkU7lHC-vO0lkoW_mX67ENKgV_qChu
HR5qPuAwQQIRInFAsX6jvZFJM7eW1uH51-nmJ6LJE6ZYrNEV23Sy8FT6DYUSYIegjAKwyYIh_EfrgPfPLp9wzl6MIizZNqpQgGGDMuSBvkATBwjM_6Txrw6e
i8vZBRat-V-_TWk682iEX7TDs9sPy_gxXGYresB3q7NWhvW_Q-uTchb6Hixe-RQ8xH7gX2oKUjr_GRiwyM1LjcVRn80YOfUZzW46XS3NYMwHJawxyLhMIe7I
fKbGBJd5u4D8kJQ1nBqkV3rOEUQGB6k1ttHX-aIS1WboC1fURw8W3tVwabGUc7-AIKXdKPw6H3z_AXZ7rNamMFnkLMwwzWUh1eMLrUnyma7Toeu0XejhMAxz
ceiGUyy2Jr_GNODzsRFGbDuO21IPI-rNbvWSKuSMhzpJyCCxCJKknHi0SpNg7fJk8Jg3Me_AdZkFrPvvS8vm_ozY7lyUMYPrLH-2VAsSDIDTr-p1kur1s8O7
vCHY1XeVOaevbvnZS5OZe606ZbMPgwClS-mCtA8f3kDNFpvJHLRysLYeJK2KamjY6ie4SMejU0l03jqpv2y9UJSnH5OidK3XENMz89MvG-MrA5JUbMDYzCtH
D2R3KbBy7wGOKygr2XLD6nW1bWShgGwyAO2PME3j7W1M0TOSPhlVgBtK5dcnBP3rSdN0CC99h2GKOZIjSEjc9oSa400toc8UOOos2dWHJ2DMiZ5r1Avybfe9
maDFvlFL9-ZYuRfyo3CL4R3SSHj5MS5K9R8vJteO2exjcCNU4LdIejPmC-4CIi5cOd9LGnddOup1krSyI-vZSUdqKcRLSEYHv4q11SMeZFDUmyMZuk10vM5Y
MGgMnjx0r84iyqQMr6LVXnvZpTEsHet13jFjjAXdHSzwu9aFb1rUCq-w1ZT9QydHkv3bWfE4dvqxoElQMP3fgLnJd-t0WG9vccqfQGsWzjjZLIjG0ZfFiheA
wm9Me1dHRJuFJSyw6VeBGEHsmm2zNJG0XeW5otXkXJ5t40rbT6m2y7gPaVIRrNXacpShvD0aUZq2GLOG1o4VnFfut0SIadO99jGLVMjusaiKMLVqIb8xqWVq
FptaXtuBFKaKUzE5Hh8saLXi_1imRRbY28sox7antTIW0YIABSHQWr5AQHToO78gsqaOXad3SKavfSlGkOYJOa6QctHai0KeijQZLW8wAGHMSqZGdtVBT1qM
RmqTFArzyGw6-doJetLrrvOoVNz6iz-p-5YX6uq7oe4wWAPb7R31pxOUP1opaIrWrvYQJjD9VF7wZpuUnLkRsmxcmDngp_wo3QnTRQbKc2tvbr9nPqub8AnO
loSM8KFR8JFQmf7CxSUOihfgx_bEgQUJ6oxyYEfnvJ6Xg5Y7S8G-4D2h_CnquAbLA0yhnDoIWh5bN0F9158yhXjdiXQKE-vir4amDc9UM9zzPzkQbrO5ez6M
e1Ulz6GzDIg-jgHRetrIIVth7HIsp0YXVvsfWqeRIsApVZbNSreqJzbndZiIVrv3fH7bs-Y6geU1gXTBOnJHooTFl48w4NHJO9mTdsKiQ1T3h8sAEDHPRjeh
gLEJ1zoNv4Xj2YStCmXSosM-q1QqKW2JrQ5qE_1P1KLS1UG98hTpPbKLj83qmTvHQVIOliNm3Nq0itI8ROQqZrPE1Uoapm1ZwyUejxOZMX-AiQrzOPx6-HEc
VB-gWsSfFIWkFIEjfTCjGCwsB3EhTM0gPkaN050RwxmFPWni3k9c4EXZC6VdyKxA4TLAqCbVcZOEfbiBNUJpiFGSdUblg4FbaxPQdrIhDIerVBphg8KS3Rvo
rZHxPwqnHYC2mE5aZw2BP3-ExnL5OzIj7ixEGLHBoId547oeB0hRKn4NvFkr2S8cr-k0T6RNYCRaPL0fEEVXm3f192AuLWiHQZiFVlIWmiUUQEK9dvK0OqFA
jLRwG11CPuOL4FaigZKpoa7VlBWgvZS2KQkbj4O9JWGH7FI1ersH-Z80jNLUIYHRfTM-ZxP1AUTlpMhOWaDZiUyoJ2JnuE--xzu7mqAjwy5ktyuBaCime_7O
zsBYsopI1Qu9bB8qMSr6THbg4uZG7JM3gczpChhaRej_uMb6wITsbVPzVi-ObbVlm8P285h4MLq7BQFkiy05LKvMKcxRV1WEjPeVNlQHbNa-HZX9zi3JpI1b
MNaba8xa2CgTVaz1TvBYUVX6TI6yR9xW5dzPB3t8GZXibqahJUewcFsvKkBTH3yNGOTCn2yncWv9rMM0IVSaiSWraGDBgQB0rnQcRJxp8o-dcpL1xPiNIkNf
evIZNbwGkhNNfq5Yng1JNoV3rkhHTCiQDomg8ckKN9_FeSxxMV1OR0f78spog1HOd-_ZDZsPPjMVNC1IurqnyU47ZIRC0ZO3IkREJJgBoRBi90s_y0zdDed2
Onr6lsOpL9BJw5gpaua4NUVbl3iUPcri0yUhx1pxOwsKu2Uaf03Sf2ddvlQGXKkb7xcu3A7wHlPqpyYrjaOklImAuv0dz6JiVXb0PTRQo9s4rCUr2mZzj420
TxTUHjYF9Eflz86tPF68HQ1yly67-54y2UmdyIY2ilEfokNfWsurX7yK97YJ41G-PxsWfj36W4Znrpk8vcUKusCGsyCjLihF9R-4fuknw-K0ubvP6ctCCNGY
p6wzgGPUPbDg0Wb-GTczKhMbJOxK0v9dd8a2d2l5hg-Xx10bQxERZL1_kgG0-6BRSIdsorpENpug5UyHncry98YnFaLKKqov9boLErGSoWTtboDjov6OPKrH
lOB32v35Dru5K6QePY6mHcbL89peoDz1CgijL5-7MGMgHHQ39b0ip9pyT_aSCjyecLm_CLqjbVbT7yswhXDZHYEGX5mgJtSDR-O5sgVZqseN8K_vgTl5_t0u
9csl47xKjseujgsZYCwV0gvC7Xnnr1B1t-JmlvAZeW9ENDtRkosfPlgv87w-JfPsZbgEvK2bso6g_b53j8hr1_jCCYaVkJ8T2jdSrGhXbe0oas6lJjpy-2py
FcBf-NPu4GfnzoUsLIIy0FyNv038ymjjdBX-Csx9FV9hoefXqVk7ZcuQpNqJRnBauSvilPs5ONGMtbsgQYugQJce-DXfQhmTwqHwa9FAAH-Oa7FoMXqa-ykd
KNPo8C3GbaaU3wWLl1uVfpVNmduPaDZDWjj9MImoRbNZ-xdK8vJVSIpUjv9zJriUZ8H_1o-Q1EZruf2-h88gE3wboH7P8PxnQ1POyoQP2iIhadc6KGpOVqlW
ta3c8pa8hf4ZWZf4Q2JhKozz7d_CtlM9YpYmxdPTxCTou1Ljzd9cLbK6yUNF_5OEVsvRBKevW5gUfDDQVsHNzHp_0IBHlyajJ_9Wrkq0fBuf29vRyW9bfMcu
LYPLVkrvzV8cLZYz0nb53i1MztDR8dvCKH0U_KLr49rbrL17XK2Z2L7hiiqbeHhmQxDcEgjnm3horjAKGAQ7DuChZK7GqFLePzJ17I3mzm2aTeVZXQdDaSrt
l9m-kjR1CJFIapH3_3zZdPvZAAibYHyUCG5YGm1iPYAf-7LeGc8c9farg2KWfexJWeJDGTn4PTRCPy4IMI-cLb5zXFpCDZv-Ld8cS5mt4LOf9D0_s9zt9QeE
z6Urs6ii9ovQpQlCglnnDe6V3IRCizL2AsjTeCjQo6uuzXRNKaVy4vk6psbSyWQ6baHQHjdfoYCozBZ5LY-jTVE5wzfbR3YubVtIoIy2KA1D2376zB-8_uk0
i8PNiuUlwpxp00V63WgqZvNH1z4hnJyvYnLJ8hEkyUkPWRAuVeXYOT5aeWAxzN29UzI3U_-Nasuu-835iYPxv7xkWIRdXcifkNzkCqUs_p0hqgudPsh_jqNa
oWwgg3bwgr6SxoWd9D6L6cK7P-HeQVCPioJ5UbV59uBFeKDjxye7mDunyV1-PQ9qYrYn2oHk4IeUHVm5WFvl7NehYgWbK72yh5dD--c8kJVqcrbvLf1zWfLs
CHAn6exAHYSmqRk1Nseaej1S3bemSPCNtaVz60N4skQWr4N1G6_ErzZvQYNaDWNfHUcLWkWB78621dw1ozny55XY9_3X4TRhDBb6-nSn-56oY1zy6dXne82D
QhcRo5ttk7q9_HYxImpU6lDdieEksprhmRZQJY9ixapzFoUIvCs3GF04oklQLnZb7TwOgPr7H6wN6UUhoDIQ4yPAqSBg5Jvkmc6tWVG_UA4WofejBnHx-DdA
FEcKe9StfhjPnVtTibI2mHvyyylPQz26UDz3GCjWvr0jXXk33GJQzSDrh6_jZ8Whq4hgNhxTqTLYnEoUGPLvwSU8eXQXfqyiDISPS0ktCcg5ixkOVFXO5hAp
TMGA-DMB2yeG8hECv82UFXOaTbMmN4G1r7TWPL7izqlgQ6Fzor8ek2AaM8_wu3wmwJyXBpHScYWYQK1ZVIflbAHPIveSgA_1osCbYLCa4mzjnkEsSbLUxbX1
DqZoNvA29pp77O69KMd4CyGI_tmY3BNH3frjGQ9QIugelWemrcXztBg1VzxN0KIDxDkk04p_toB01S8ibFvV7_0l_uJ_mNy3
}

sprite $WomanPirate_100 [100x100/16z] {
rTY7alCyo0NWWtg3S_zN-vSWUvBTJCRnrvzfRrsC45WM_YC4VpQ9kPHSIquf1lpPGcv3ZSziPC6VHV9GlZS4VuQy-4717oRL-CpMU9Z7kZNyKKLvqb5JU0uV
Yf83VunCaZIIDglW888jaee_97FR-qToQMEPhvdE5X58mts2IjV38s1V_64290NtZHr110YTcusft0mW6N5RzqSD0EBWeNZqJM1a_cCXB0EGnjE0029A5w1a
lH_YIA8OJzRH93PqkeH9TjpJZ6GN82m-cu6vCWowZ76xGUBHmDduIgBKX4bNqEusY2Xz2QhnXuIGW4PNKKYxNOmXGE4BKtA9gWPIZJGsH99oSwLKWCJjc7v1
oI8YcImxLxdP8DF_N-2h9K1kQxPXiq0moGNehScRw7jUFOLJHsub0J42iQaQINYaEsaeW4utbJkOcQqM4KeG92aqCgAGZ7UgaO14Lu1APu3aOTwBlkKg0czq
uV3azmHFE6EG3UF7DXZ090s2RmHFO_ew2I2-Q3OdgVp1W4ooGBvF8v5x3QAIP0tI-8kH5L1Ilw-6GFdSXasEZhVPQyanvhgEH6Jlm-iwkO32tOQ3v0ex6ROW
sEGOPGMOD6PS9buD9Ma2MIGRf9AarJVBwlzCIOkugf5pZxm8cQGr1AKF-WU9AUUS4ewzDu1af8MlqX0ZEHuXs12L-p5J7KgUTEcnlOilxTLgw4uZO7YFcV-k
B9Acut5aJxdKlemFjiUdnI-guIlGZ6o0qiXMZ9mv2bwaHT9RDj5e5zEmtTQn-EWUT5e5Y2d6W2U1PnyLaXTxetWbLp3QsOlaYaXpHok2K-TUIi0hyv7umDrf
r4LgyEfxFMDlESL66YtZKFYG0AmhdmcLPDmrdluV1rt7mOyadeflRjBOVQ7xbLTJ0ngt0KHk3JxqOW3A8YS4W1Yt5SeWEV1PCd900ZVpnJlZGN9k-dygWd-5
I6er9ZwP-AYOTz5yUlJCWvvxoDeOS6kK6YCFDZC-wYGr0Fqv3QMpnG04KicMkvxbC-gw-eKhQXwYy52VqXYH4q1OavQ0LG4W6gsGFh9AkFJkMpuHZUvvsQOq
LW1fcEOyM7TdBDJzRoy8HdPWyBIENJEMSa8a2e1GSoqH3sQsiZ_6vJarWCLJEPQgbxYOiGbELlDOStgNNx7R8TVQMXzZ3l7oPrk0z9L-XH3jnrvfkCJUZ7yZ
cRjMmLlD1BwyvVe9btECtbkhjUISOo79cic0jyI6xn8gBYd6jmmGoNWhMj-RFNnnBTNdKXuywYZD2du8rVlyY57n9Gcfr3EC3QDLl4fMLq9WyhMoWJkuMPYq
o89NTUKewvoQ7NTCkfP9bg9u9JwVWRHxy8v8bmTfCr7mI-x7-ynmIw4hdUGCZ8A3fDfhV4ctt4l3-302oPeOi5NbmsmDw7G3DsIZinXxag4uBMkfJ2CfcLkx
lLJMI6g9UJ3X58mwKaYiWKRIo2MtjzMeLADvamaEoNDK3Be2t0bY90rBfN9EPkCCE4KFUzQitBykQSACo1QifXy_ARTUCUciumOP99cp0U14ilF-v2Guqs35
3O4qCfK5W0RC54XI4vuCRbFmFKdUuga1YOo81OjyJKLuQBX3I2CR16Wy3Y6koHvNawSi-DhnpR-BlxnX3ZKA98q_UATVwGgGZhTSv1FZYu3lBJe5oZ6DihqB
SZ-Fyx2O4Oy7BQJI6GsDp-J-kuCQSEoSpYph217yCKxfNWUwAPqqKg0CGBNZBc3mMRnvpKwjULADiP1LzWrLp4cEafsitvfLN0c0D6E3aEniU6PqTwV9yq53
2e1ntbEq0iTNwqQCXcV1ZYSTzZu6vUkTEtytPVPIwViOn7VUDUxScIM3czHifD6Pu1lbNTz6ytg8mMKQGkEf9y5rIiLlUIUY0ZSOWD2C1ni95mKouOtisVK0
9wi30iGsbDlCLokkWdSI6u0SiKaGR8bKZpG3BbXiUC-_T0BU82SGnyKvBxVU1eCh2wHVEvKcshrJfN6Ah4k9jFqWaaeRS-bQggkNW8_Y7ldfqkVEOWKGEr-P
PdmWVEYelB0EP9Pz-jVPMosbrAuaQLLm2gN6DsCu8DC4dsLoaAIsX2UXwOy9BfNM1GVbGmtfOq444AW7Y42gVT4yeL62xqpBE0MbPK3s4Xit2_Wa6aahW3I-
ifKyoahdhOaeBJvbIPsZjnpnIJiEbktj6QSWAMdjJ3kI9dj_M4zNN-EQTZRKLKiPV6OraEGAs2QfQkIgyN8VSVe1rwn684xZU_NrWqw-ELDDBz_8NjHO-Oln
_1eGcQHcmMMBL00ebW48GkdA1vjzB3j3-4fwrLR16uAt91udZo80a9Kq8tckXkHvnZ4onsbQy9qGvCAp77yJ0C4zWl-i_mK
}

