sprite $ninja2_100 [100x99/16z] {
tTU9Gkiw4eJXqkPDKltl_xIpnIWcX1Cdt30pzplx0gLMMssX_ranw-r2Rh-GajtdyFOGx5bl5WsBtYnrcCClX4nlhyI_4-AYDyk6h3Shs6yFcQ17lTcAhNVR
e0QzMOVrDwRA_0lpaQmtMx2Ztgn2VNzBpFBtQCbldFVs2or9_9Md94rhRRtLRIb9LvCXAUZdIkEeBober-sc7qiR5-QgJU7PcHAdQd3RYcuA3oisT_H9_p63
yuc4nLmOJpgQEkO-roX9uG_FLXo_AOPB5MkrwJcC8XR-f1S5gG2JxYeV4IiOMXcxFovfeV9z5S3UYVhTIPpcFQB3dh3BRN_5XMuUMIzjzwgl0fUCQ0nBr45O
Q45ICu-OUXaft2bazJggSDQDGW-gdB99eTzhUuQ-HxX5VP7T5im9Pf4cJD6D2jIouX5n8uCvnqLgqB--9W4RQBglcZCCtU7Uyxi1TEoRYBnsmDiS8fmEOPKg
-6P0D0nyxbIOpT3XT8I9Ii2Yp-O6j18qv0v0NwTIvWry_HHdJias2Za8GLA-XcAWvZ5DTnvfV-2WXDbqHru_0li-VtPv11oORvXf5F95spuYkl6cOSN6WB5v
h4eHxXLIwAEApqEz7fT-8iP1gk2eMzsE7n4zwQ2DXxyqpaYw-sYf63OfDQ0b7NcK8PNA0_iaQVxQaGRO7SpjGB717mjKMlmWWdL_KBQ-w20nzA2W8tQZ-hpr
JnqQlpcyH_HrkR6E2Dr4YA5U8afKdDV68SZGjoNB1kh7_MNM9s4pWBUeM-RYOuSRj5cIOixpl2phFCqbXX2Jr04sXPMAtNKZpUisfr75LMSeUyRNoHhNZlT_
MwMOj01P9xNFBrDDQpMcncC207lDwnX1cqvQ6SQvIkjn8iM6sroIqh743GX1fqnSBTg5qhUnhOkNg225WZrsQ3OiEYTp4FQ8xVZnsVjawDV_CpN0w9mm3W1Z
LXQRxLXfkwp6uAQGvix5f7Eg6Lma1QdlTOHBuk7SqHfZKMuwtn2pSxeKDqr1cfhPiZHD-hZdcRq4sviXwHnpuAnThW3kywMO3ZuU_HOBiEgS5VF1UCj1YgLX
TgtMCRYCmNODai51fqGE3Fuy33s-Z_VbllxpPps4QdDZ971xPp7ZJPjEdlLI-SfuRFvDgZ6kXpaKJlJYl57G5Zwc0NZH0mjdZKPzccGszV4P7_qzoIowAdE9
Zvhn_4wHzPoPiupDUAqSXOTr-EpzpG2UWvuLpAwtpWDcZNh1niKQ55Vp9rwJNX7YNiN3ip82NYwawZymtrc2NfO1Q6CqVAVf1ofWZwlMTopzi127CUE_evze
06alwNibvnHUBiIOIK45-z5GhFdrGjR78zXWO7gv8stgc5E2Nb5vOiHxaLw8cMt0dBFf1VD8U5T6R9Z1F61cdHRsEwS1OsnEST0pWk86vXakUivay4Wn9pmP
aHh-jW-zrUrVQhikmyzNCPjxUbtASJ35QmBEp_HQgMCmHwvprgtWQvbHJmWRlZdPRRuxLjF6LNgkrmQkALi9kc_3rwLuIkTxZGzrj2deMpTV9_HqRfkUkd3O
uz4-_UmMS-0rFDxMRjlTji5H3-MpX_PrOUAWJtg7i0nprb_adm
}

sprite $ninja2_200 [200x199/16z] {
xDXNUlKW38HXoO0BPRxzh_RllTV4Kl9UdpRFGGp6dgPdRbOso-7iIPBi6jKoQ68qIw0kM8V5LoQWqoswRO9W50lE9mBOBReqGGO8b288GBFWl0CezZ_YRuVz
ZUOMcmy4g6MPaPgWHn2YMdGJW5N33_j2WBOaPwqLFaXP89WUFWW2CS87QI2WXmzoyCRvTlW3kn28mw8R2A0bwKEA1US2q8hVXm8Ir8Wt0QXRTAS0E2sw8N9i
MaiWLFBCUd2DDuP5T_5-rZr-hol1hBkIFESM430jkWE1ujUX3r26Ejn04B0EyxT8SBwKu_ww049o2-v8CY8-UMDFiR9kV3xnhRJMzjPgtVmNLjQqsodjck83
WUQrR_OT4mGSTYVUklYE_kqiXRjTpVa-0F5zyt3xWji924s_HuZI5uWV4lHgNve8tMHbrSwlcktBzmhuztkMr-FgOyxHZ-hsIye0-ECavx_VixmDFhMEpNx6
BtxNIrwkH4jM5GPEa5qf_lzhtzPHeq23R_3MtPVc6CbIASB4fU1PCuU2bY0yUSVQMTxYqzcDenZtCtccPwducJgusu9alxTrqkvH82rqvgpuMU3NuZLx1uGX
mXwqHmor-F_Z-BYH-o7H6_uVpPVAFotf-YJOOWXXJU2_TLHRnFCpFGPmfRcED-bH4J5KF96_lApDBMVs2kaJyPKjMUMd7WD8wYhCFUmDYzAfrYmGbdkTtghf
H6tvTv23CvfjUq1FRBxPiKXQLpscToa3ELpDO4_y5N1iG7pQKb72BLR5ysowaSi2LoffnWoaS8GwHAWFn8dFkCIgFLqShdEkTyOXWTFRhn58L7NaHEF2wjNB
S6p6qfiyoac9XdGImkudEGyhfVHVZY5PZR7dSp_2Fw1sZZhJaETLtLvFvZJsdcsa1ldzmvu_DjUGDUVHgav0FiE0bhr-0-g7njv2KaofyYHRiEib6iFZcE72
a3MEogU6Rzdan1-RjoF8-bdkNMHU8YxYZuRKz1vDUIf0JBD6ZjleP-EWHZ0cx2xrZ6UQQGcN8VSWZD4iPcCemcmOnFt6R4EGxNwotk_L5w16xFoZCJjoass0
IBSiddIAOSmG6mB-uR_B8DQ76ADtPa_MhuJ7dcu90rCqhivlcb1slMnWDEhVQeNy1ZYwxISHVI-6uQXwkCS6LPfr50q3l8wyn5pWc3VXRZzqouT4cnZgjU78
UC6AdUfAlgSwueRyS5eU2rB8hu7BSqA_6D8FXOGzDCoNGCBvFQtUA29IsgtfLKECf8jBLo_qSOtUKYlTBfys5Ym665MCJhq4hiT9_64GdaeLnK28Ft4fYCsB
W3hduF7W984obQQTtM6EglIuL-7t3S6ZLdqjxLZFmAZ5JtntFn9t1y-q4ogFu77ohr0BdfHV1FiIyLaRrj7jk3DabOxCcdJTyXV1157MaE616tSrezUGw7p3
x8xgurXSr0TJrePhB54IyLQ7QMdEism1yORmJDFeVQLqqmSxTtfzfGWdhZPpeFcLZXyahBTPc-r8L9fBoKYwmlfZPnPvTdGth07fQq_FmXgai5vYgtkqdRSd
ySeRmiXsu2Ev4D_k4yf9QqDIowFDDfKhibHsbGo_Pnuu8XC_BjNjA57rQ2RwQKQauzIFsS-KCTzwNBHUnoCxv3KwvMPKIPAXY9mzlgKjLSt-NHshgTWm5YzC
wKLCANh8LBlaTAPrzKroGB5ebmZKFK62L4ZIYeubvQlKbToOtFTEFSj-2UnKJ-qe-RMo4Kz2EpgnSMPV9BALYAPJp2KWOkEX7LuU9Mgrsn9IFn5ZYrOHCtKv
ucUYb1-wOXROvj7hCUZa1lDvVtI8Ns5DQ9pLXc1KfIxPGtcN7BWDif3E2Quup-sGKUZtnPPBo6XZdGyVU6UDNkZuDovc47Pm6aeOazzLEFT3zA-FxSZsQ8l3
4R1H3p0ylx9NnflMG1ch9iUhAUgFuMrRsg8TbNTJDUcimbb57_QT6v5F9rDVxsNLgeASp4HiomDbTKssVnkI2r-gPxyegC_xTWYPNxie4Y52Ywd9s5HCGXYg
lBG3DziEDy1cIEcGZbfFdG4f9BgeOgZvSNhfoaQ_519pBLlN-RXrSLf9qbe-ikMqeQVVeQaZj4OlfHsoVGQyeb8pAv8izhvmSeXy5G9_wAQ_fke1MJ768ijv
A6avE6fcOctmLbyfiorgb1DNV17EDreYPxzu_Rdm3TuAgWceIDN2yT406BUfEbqK60x_kT2TllggPwFg3-56PaXCE6BtJtKR_T3JxvFMaKpP5w2Uh-udcRvy
7JeS_GIRixqT8FMEE38xiTKuXqnCYsobD9cmIcbFbCkfSBq9FGO_WshUTRRopUnFleMcp1fcNmHgmfQZcruSmrkM2ZyZAhwOL6LRS6p2TKuxqVoRutL0Nors
mOZYBhxKaWfUoVsjgn9S0hVTKFE77AjvUA-tOte2zdRgwZCgIe6m1BJNz7NkXb3dm5L2wWMCA6qrwUfJfPYoqKwoCJlIsmCD4CrJSoWYhrO9hQijRB4P79AO
NjENnaW3UuwdouMfEj8sfD6lGaAVpzwtdXuLh37MnMr8J4HxEy8j9FLqReAkFWZ8Y7q-uS73XoIxXVZwXZoPeC7VrPtfTjqW38GhRnSCcdd_f-sQHJufYMjB
qFjbpo_F4M0ZZyHv3wcvLKPqrrXn_YA1Yt8UXsqepFyycBQyx_d3TRWRcd3mXOd2jQ9jVGam0GRHs1Q-tDudnmxDZ08D6VA-xKa-3K8HB0CllrWPDjy0TP01
zYAr3OcBG_kNQF3o8xNQ0G4e3e-vyQ1fffYKXCFv5G8INGAoj1RyjATLxYT4qK46g9EvRmImWz5qQJAilHQg9zPXV4RHYCQxgtVfquBI07yfklLiLNK4e0DT
cs_FeNRzEdTkZ6HdPTrapk1TSBJOHiTbemL4DdNGDq1TElT0CyF9L9J9UcUarTIzOLIoZYrR_xbSrR3ECgHfRklrKyOjH-M8WBoHZaFk4YyX7HaGR4rFsddM
SQSJcEoI8JlaH3eo0t-_XiI02HB8RbtjXd9jsTLHEkR6DO3N-3Om8FXexLfv4HaV4Co7OVLC2-_naZTpFxy8Fhgs-WSatmu7M5MrbfpJEiceW1I719rzqLos
hZeMy3ZHDxSqEnv30Y8ksm-2xwJkNRvVyfSFfIjRtu2yD6XT2kW92EdTq1_K2hgJ-zxKervCWLtt8Uyo00GKqdSY1xslHTypLMSGGHavXAzOxRQepxdoJZj3
cNi58zW689sEd0RZGAS30bOb24GAMJe48uDaxBZQEpsmWw4KwR1CmVZcOz1m6MjbEF4ofinu42n3_YnJvm0kUIp1-0EiftAfXJQrxYybmRzPbb-EtfPCXET8
7_ywkQ4bR_CapTQB8rQgkVAq1X0bVVMgRCo2cqZ2VBN7Ece-LJED0VQOHKzjCe3oMEHEMIl6Fw2pfaNk-h0XeVFxItHVnQ7e6ynHGfRABq1DaxYvuiiIeK9I
QqhWPSPhcXqh3q42EMQRGR19lhRv10tXD_IvVABXLdx_qtKFO7OUKcZb2q6OCYuN7HPr7b8DmFeGRqkTfNWEgNPDdIxYq1C1RBB51mE4KN6LJQ6grQA_mMyS
Ms4WFERnrAOC1AVv8ifc4UimYaTASvjQ0g8H_Ze01nNGFKtFTjYwYFpwRlWlB_C7
}

