sprite $ninja3_100 [97x100/16z] {
tLc7bjkw3cHl0A7__zjt279CyzYhv-pTMv9naS98Wqe0MflV0DQ5uDtVHHvh5-bTHBW6-zFqlYcxVkcxXf-aTssp2uHG-37wFFpI9xj29iZ_07iMvgMpaYex
n73-Ix48tlaCsa7A9OOGOYPO8rBTz_c9XrysUgkDcQWcRoFDe7GX--siL5zi6PDnlRFrTQsG-nv_tfJ0KmWkgSvpLmNQTxnV5x7AU8LABhRDqDTVrDqNdkhg
P-EXFZxiotHP_9GvLMAGR8_q0rZKarX4k7V-p2jJtwtdvjiXGCYnCKeHaQld_qiVwN5hV-XzEWcvl_zZl1frOU4FIetU0FLXmABRfa00F0Z9wLvz5hY7nwTD
OI_1xVFp96aRSiTVUUaudP03I4uWvblaEC1ZzclruUUhp-Isl9pyxFlUIcvyHFtPXAypDP0ykw6C4YIJaq60dLLJY8McSv1GC8ZB-tAZmGL7KotIKkaWwdsk
SetU9KZP9hmBWdMLBzakY7Ok8nXNw930HAoKKz-MlVEfCPHJK-YbIR78aayrEGEqHy_r7T0GL98jetDDteKyYf56Jqu1WJhN76Fmpfe37XjARDZq8ai6zlWK
mpMdL9hwBX-URy5yWOOEa8pT0l021kFL4PkBXP_qT3LzdRCULOYjIPjFbbNu3hajMvROaKEBDTtMfM6k-hICS-2bNgWkcP0WqZFeJRAtDGd-7IQN3e0NfOxX
x51NTgN7oYPx9oclog8RRWUvCKk_86kbfFNHQaHpRTMZevXxy51-ME6d0A3cBhnBNZ6ETFl6KqzhpJt2o8mwxfpv14ZdeEcrP5HZBElwBqv5gZp9Y9d9Pxdc
c1_Pf3dZzKnj_HXnUA4EHcTCklWfo5UN4XgSf46cMGx5cez1ChHR7d8hghj3Kiop8KqJB4dsWPZTfoAIngtsBb7jsVox5T7SXnTPOsrRXJH-9i7f5iY3KM-m
hP_5YBjGQAWQ8_EpMlVXw6WrJIZh9XZ8PqycLZDoNPvJNjTgRnzwA4zhEqjtS_JT0hIonphx1WigKBOZCJxD85Mq9kbIJmCU1ITD7J3Jg53pwIDdc5xsCdFK
nqGeePqmB-KCSiWLZlT-trLQhtUjorKrd_gUVOZckVHID6rEo_87DlXLvTCbF59eDotzpWtZLMvwE2OMblg1VyRLKHsKXZnuGgPaJtW-pdFzd5QpkKUU2aV7
r-pT3lqBzPyiBPznVUBdQofXxb5cAGYsTTGkwj1-dMIBWa5735ZK07iNPzBcpS6KeN7KDLilA3zmzUwdLVrbADP-VuCmjmrPKyUTTIu9qV8FcCW6vNuPBcuY
WEqwX_iYQtYopyxNetRBFAvGmaEmt1imxnb5fGhBVAHs3DSBH6YfS9OHbyE2TCFVS8MjNHQ_IN8-2k0VpKHiRK1tmOr_b7-s3csxNXUF6GLdciO6E_hPWFYU
6qDYS-eKzOBowtYYj2yoo0NyfGYuVGIlVUYi_7gRDowL9oViGACmLOCMjeSDUzSVLRhrqmNEDh1HZdxsD1TB8sMSJaf736vhQS13LPZw-RmKBU6bbQQ6qkhq
i77ZeDu33D4wn-gJ5eT9gLHYPg9QKd1gIcQLt-eq5sNZwmHAQnB8oYjLlvktlZ2w2qPrhdffui59u5vX-nAI7_eBDcS8LKdsBWERSB93AMWVT6w_uuzazJ2v
LGP7HZ_4uQW9pS-vW_ieZAJbyMkqiFfOXmXQOw6wjkRvx6PzpCCgcPS44_NgqLJh_KpQPg56THJPxQL5Pqxup3pj9Ez9pxmnxexVQe6gifs1_L_SIClIU6tU
aeDLbwwW5pVoWNimrjn0jr60VtQSapMXhTNzeUnKn5pFIMO9kuEwZxVoU6eATIVEKQufQPxg3Qm9M_ET2Merg9V-x0FrPzvTTV0OMTTA6mVhp3q8tFhc5aZP
ODK1NU5i0aQ1sMHluHRLUh5gf_T2ngwfo6OAbdQ7QzxS8Qqx7uJ7dyYufk2Tyzw7E58AnbKxQWjGx7stLAAZCSvJgYcNHjmxCxKIlRMnhT1mYF8q4zMlhPXw
fwhys0Tda87UkGGRsZIs-1M6-zzPh5xT33_v64BElnz0BWLVPhZyp5UKN8flTu8IMGltWqq18uwe3t_6gdvD305w1PDvnPgZtIxERvJUpHbdhV4uRRp4BYFU
13iCJSP1xpqj4CLE-MqMv37h4H-9xroaouv1f4Ucrkf08uR-8C4Hbct3tXOcDwTw2mkuQTbyXWknlXIFxHWSDSxlicXE1BFC7otWPQIOniZfnzCIyuerjP1G
-k074Tfy--If6BvHaEPYSEOZh3q0rbso9loxvpBpQy1MngOyaDvDTj_uARdq2plzd57pcwlPV0Csx-nyCaAAUKMrvhiYEZm5l1tYWpNVWwkxazuEmTPy5uxW
Vw2P7qRYCyZL_3ISxek_HG0GM5CMFvR-3R157ZDXCNy7x1xui_bxu51ea_cxK6Vp3EPlGr8NEVFtmR4snxyHZZgRlnMsLlCt8vW_1ly3
}

sprite $ninja3_200 [195x200/16z] {
x9K5bWCX44GNjwxY_gTT0_Bev09ZFnct-kZNTNXuCDQ7b4l9EGPdpDdYsr0480a0_0Cj1NEUqa-D1FwNpGBeBTep28H6JWEIc3jOIf8ERc6Ia22cX0PZaMeF
tAAYRCancFlAfOM32ZZ1R40wz1BPpb3y4TjGwIen5lm76oJGgpkQGP2HVSNVQm3ub10W7sAo-CtW6j6A42FoMWPZzxrYfYFa41LX73X-NVLTLVBRhbPZFe82
CHt0BVz0MYtvbr95MRnk8yJyL-KFiTQXs3Ye1468lZlw_wzznM84nYUT4okvINLdcEte7y35d4BmQuG2JtOF6lzp9hPBA7e0gdIJVnMQaggECV85abRdOyxb
VyWv-3sPhVdWI3zNIFX76GogvnIullum8CazM5Ji5WJIG8tczo5pxde5CDq0LBEprhZIbayPeFxNmsYQwv-JzRy-labuXE7coygVN_Q7jG3QBE5SXJa_qzUX
qHhZz_yxsUKtGr7fmLzFGG-W9bH43XA53KNpRVkRLGJGq-i9ZYtdpIdaIZ1ctGwA2aNvfLn0nwGCRuX0mYJGub5Pp58VD_cCP7uQIvIf4_W4K0t6LYWeaiBz
vEfTo0BY5WgRAh8rMQ7O1CfIusxOnOTKP8gITr200AfrCKLweaQwkOTFzIaKubuL086ghgRWA19LbrkM_lWLfBSjOrmaFgO4wXfiGR_ZhgYqrWrSxbabX0yf
T1vnaIR3RHxjXH6YBxR_ler2g_G4I2l0cAJv3WNstPXjXh-9Emo9dLA91mDyN6Si6KJJbjjFOcyiZLgzHGqAg4ZlbpwKmSzMtxrODssLnNiam1jlK1Zfebhp
0HB-wBWCsXbVYJIADrMOvsN-0oEg4EXC0ST6jHB_R-Y-_nxGquv-Q4dnpxqmIxbeqbiCdgpeFSfufY3scn8KXeGd2joXP8r7gsok0H7zcWx0Q7JVJGqsjWpV
CLB9pXYtFoZwLnI_naeBUPy7y46XPBqS5ezNP6UCiTf8lXNlyseVnrHus_sxyj3wzKXQkJIciF4dxQccQ0FbOjjEK3Hk_cCAjeGYO4ipHRdUmqsrcEAh10hT
YImE3rELQEdh8mLq4lX3gyOVoTuQOrqiefYo3E_e3mmKbg_MGsCSVnhhbjKqECKS0sMYCBUMV2ZxvJ4vpeNhdwW0ao41wrSQIOoxC2PBhS6Q0nLAi56CLAeB
CFpkb7OrbeSSFjTd4kJBtsn8t_NXqaq7JoszpaUIKUTaZUJf4XrIYj25IEZWMTfRkf15Pm0OAQItrfzfiTCuXHOyma4nXP1Yyo0TcK7oezMZLljFZnAoMvMn
Qon3IfjzuOs2s-Knh03TVckY-OmeIWwa8AjHDYbatlwlmSNQxGIamQ2dDQsDHwhIfNoR0hDOVqSy83N7zIGGh81sO5VQOWwgFJBMiAnPfo0qHZ5eRNeilbIT
AU2IWYkxOZnzYT6lRh6Nd6MCF1mTkjDX7g10JOxJ0rfAruoU9pci2wEk3XpZ-MBMYeUINxee9G1pDlNjS8hKHlHx9OUGPGvPdIV_b1JzwcAXhDdPyp9Yqvhu
-Bkm5K_Up090k6kl63jjuV8fORyzbRIKPZLdM0KCzLz2PE0YeEj37DcugpC0_YQuGcbxVz8NuIedh1LbCT-0bMcpcxCvaDg4fqWqdVCW5NdEGQJKWwizMKVw
zj0uO38OwAESptBb2_gyFBvIzXYawAH8cRTFA7Z9oxURKORr1WPjRkPfpuRn5hcrzIsX32NHiwsrJPyagAlvBXmm9G3iUKalVBdJ0vuUgAR31IR0pfWK9YmV
dOVAqUamh9Vs0E-UYl0-SNe1PcksBWgPibAGF_dnyj7LHO1Yt2Su5XrJr84CF4bkokhXrKhiccIG6DNC2C5yWiJP9DU6sXQmxdkcus5ib8iX7bIncXcaKVcQ
OYR4rNm2swimgk7vcB0U7U0B-eedeBdHOgmrriLSintri6uDCNetCrWetFVWcpEZid0MQoY3RACpjCowdiu86FFhq7N_tKIIDP-Xq8RoN0OlMQVaZ0U9Q7Fx
JoUmhRUbkmp-5Yk3-H0EpLWaqpRMO_YgKsfhXfPvZIenSZGFP2XKcXJPN60rdwAmXCYLYzpDiYej35D2KCXYyqdj9Bm64Tfx5l7cvx0SFhm2Oo_YBuyP48mJ
BfBOsOrHehTSsVmOqh7FdhQxAvlr2a1PJ0H0Q-aOnWc006nZ5yQ8cs713hsabgB5a08kXxoo6YSAOFBtTIf_gKInFoG2M0O7UPxNhhZW0060OYdYw2g5k-qL
K87MvbBH_0HSBtiS8E3Kd9ju1YOyRrnzYLY-Dr8jegvLcJ5lHm4BjXGOMyUPnWbOfOhcnQJfVkpRRHcMQrgjYMpMxeRlno-kjl0IHYCx0rGtA028DwlCbnjM
AfbQk9Eo2oHtEuILet2k2tGt9DiVhdeA36T3nZuDzPys8iYGJJQ5c3l1e0C8i2RiLMan7Ui5XR6oTIRDRH-utKiz6Fo0AQtz-A0QzW5k4CdKlvpgSmUY2Gfv
pkBeGd2UTl_LvyDUhYnNAJGDwP92R-AAzOhv6SNQLcieH8H6UYDAFm6hHcMduwS1tmbaqnG5EAnVLwzGJ2fnf9LaAPlAtGp28O72SGy74HOez0A8jbsABhef
4E986Ti-vlFT9cKnzsA5iXBTaf7c5k7fa1suF0dFPXs6IIW5puQ6tPgekV-X0XLG5HlsUWo3r3PTQz1ARfuTlCxIZYrAEuLeReO0XpCxoorBSnznnK2XOctb
c6Ygkj7z_J66z-P-LsQRW6GowtxxT4OnkIT4mEKJucnLRhZYz4ADOEzdq0-rnJfEgPhM8TS_JNkXDPCu0Lrj1GwQPnIWyLuIUJm4jaQQ26BR55BcatoU4wPT
hr4TE2j2Jy2LywJbJWRzwe_DcNX4ySO0YXslbvVxFAqJqDMIeiwOZaQgjpSnw1544SnAfwiF1dk68aE2iiYIeRgDr23UCJPSNYMvGQ5blKK3hcUF5LMtiJfY
YpKP4akrOX9UOeyBJSTJ2dqdFlS9cySZi6JipWXjrcFDiVv91lv44r-lTR4Pk7A5GwNjynHj2_fe6jaOVrGPzXW7y64TG5BGTUQWWBZkvTUbRRwdn-47PsCS
f8b06zsEelbaT2tMv1UEEUfsnG7aO3-lYsYQcqesPX7TzfN-bxLhNRTL1Q4JDKqbUl-tFTzCREXgromx_6YlQpi2v3fOUwQZ3OGJ5eHNJgN6jBOs8MwxNak1
toD8GfMdEkMlK6guq_-GN4XX4rXIQUBBuSAUOKpslJj0jyWNmz0lM1JQybT49omeTrJc7JfpZ-TwXAZldIMOZ9D6dtdULpw4ZjLBAMXzb7flB2hFQnuMytPE
6pYxP7I4QajM9077QvmXXPMVLj-ttCvsprnyooynl142bRgXNYHkPQgIiAzDIkkpV3-TmxaYRLwM5-g7o02kkE80bZ0u90pmxeIaJ4HmvrpFTcQmS7wyf-MG
uLnRSnhdmE8bRV2caZdl6OD3LUasr4Ai1eJDVCBFeXEzC8CQVFAExGl0oddI17rvWXR9f4qK99nNBCWhA5Z0QE6g8jXw6wMArzoOrmTIa52ZzXlpqV8Ednht
7WYGw_CUZJOSqF90aVI0X7bSahpfBb1kOjrab2jiKfYfhsdSbiAofar7DmRkI24FmkzCBlgohAXdKiJy2ahb6dK_mMu6jCXlcFCqAWFaj9vgkBqM0PIWatR7
iMoCtYHHLPfOxh6GnYTSr6vtXI76AOV2bs64ptS8uEjqamKpcXpKnC10uHV14G5Ucw7e0roiGHmYsQW-qlpYN71oZt2WazSMBa9O1R0qCd2T3EGmvY-Ow6mX
kQMLdCxD6R_COnnaRTkqvNOSHNjWPEUqzuVhHNf21eyFPT7CrVwImVZgY5n-VmPFdo1_mmmtoyer68AVrK29ZvFQ_O0vowGbZwksueXVHXJ7bje6BLSEXArk
MS2xLmbmchqrHBInJSPE8J64r8P5icdZz2Ey4yaqdYLt7TA4wJx9TWkTL6NW9e8rvrDfBP83xMhDjg-ENpiMc-wDKnoR8jfx-Sh0SW_LMdYsDn0HY1VgrMt9
tvLJy-DjjAbt4SlU567pcPMTskg-kwNF-8mzRPf8NncqZ88vlQO1uA35ix6ngjmi9N-nU4JhV8WnvPnJYZ66oHgYdWljCQFVo_8dh6xxqZmuyiXjJO8-hhaz
BpQWECSe_5iVcVyDjSufEEfWVliDzZmLr24O5ZDS-7LzwW-dArF2tiIbC40sv3_WFoNuPKKPARdK9AApT2mNPLMxdmRd1RapeQc7UrURsA5bKzAtTeh-nTUY
8m0D_hMvXv57Ymmd2R4teUalIdVd89eFkQWXVmzinyTwHNAJ7869lx3MrUZv9FmYrpG8VsYJIR_9IoTIIluG_s8nUpOmyD83PTN-oSEeAzcF5pWD6iwLNQzL
qYkvYk3Z8bv-epwzKS3vzSrFJrhT-LC-caYh0YkF5rtGFKRAqEXHhINPl8SBk1mXjIVuHiKN0m5RAMZby0swtxQb0jgZcxwhmHNwsQ8MwYnCdltah354HCQw
AKG6cxYTwXD5LFnhYkoAIwFXwH1_wE13rXMm1r1ccoXm3exEbo3hhuET4kzwrjjWED4LEw3HyuWQTX0XWn3OTNbP3lRNBkUqF_lks2BHnzJ6DQPStVoc5JLt
mPxIGQ6bNKp1VuCaAdIuEVciEhVpi7v_CsfwjKgftB_4K-1Pj5RHST03C6loPVPWn6pf0OZp1j44sNZOWZP_BHWE9tpUCM6uFLsHgO0wbMvAV5GMXNMTpFt3
D2EwgDuBgEtioiGjNEORWXBgSCZnOEnwi7cgGNItVGRIWlMmHXVqeHatgk3kYWZQ7EVqXWLlkzFe6CHqi9tiTDzMBvlAv568QQAAB_aIlA04ygoE1NvvY6Qa
ddA2KuOOVDbPVfMo78-3w51xQjqYEyirmikSntdmI9NnIa4rfAljAgCTh7ii8BfGnomBhmYzaedwevccyStK5a8uSe2uiimkJX6QTOUWR3FLUOwYFNgf6hc4
3xd_QIJ-f3uetoxDb5eO-_AGZKIgJThPxmjzEDg7oPu16BM_6ZvM9sqVIq5lmviaADHtqky_4lu_ngQE741f74KLqiWMjY_LyWhHLoaHBY97ftSScFfk_ctE
TjRlwkMX621VTjlhMe50Hm2Ltnc3EuuK8JtdW5Zl8G6YNQFJLFeaqifWzz9l194R3_Lq3vwMNMO_JMwZoOSvxxg2oYeWd9OhKxsyUTp3KUTa5tcYuvoy-VI4
62ftM15zvcIsl6VjfLgH3O-PW6Tk_gzuTw4QfszGQjpavvXoverod8EtPY-O9Mpeg3hZqTtk6xKQkD98PRvbmQTxGiZ1XvIH2w1Wlrqv1Qi8uiYxMQ-Yg1VN
Jn6t4MAWiOdifar_nnOGHlpDwFhGKDNCplfBNCPMUVgOFZ-77WyPDkEON2DQIHVKxxCG0I-5OF4rN2MVA-_wgWqV5d8XnOlseJM31IOC3lq-ahWDnUKW9dIg
ijzYHCHuYsHZ-9YOu21Bxg5Z4v6AlavFDcsY2oLd6plqykN2H633jY7wFyRSRJfxigt6efumwzWcaf-EkXUC0EV6LbkHyc9DRdW8b7yqqir3l9e86tKI9opS
D7CvtR_AWHpBNinE9ijbm1BlfZtAGibX2Ho0XOwk7hMZap-rCFFUkcARBtsft6T1K-Dj6cQvO64vAiu3AQYeSs1yQRgSxX5xqxDLYxJOMNCXXVPH7-n7RQqx
DpY5iF35H4ruq2tSwcfWGUaVvdpyy6v4XQj-e9qvuNCfv3iCeAzZz8ZzER1sPE6NkSCFrWWLl5pQ0jzl_MCOdaJE7ubpYi5FpYfz8-kOClzYeNU1WcVNopdh
vdwWAcB1Wi1XwOLJc2nT_aL5FwVSMYvwvh23vodJT3_tH_BQ1a0Qgjdxddug2nJxs0_My93k8XXC_tUjShi950dDVIBh8YD4GZGum8Ba-s4UJk2qgsryKQwb
AJ9om1SyF0YsgVqZJIBe5u-J-Q-ziz1n60Q2wAp3YUty_zSUMnqTRiYwaVAAmdOIyr9FIUZsLZ8mzr5UfAv1sMkFgvWfF7Wh_lpQ8vjC4Tpx3N-ct9ZsjgFK
knT9FVqcpiR69UTz4k883xPIRxw8Pg9OSnfqp_8RZZNAMLc_q3pt_iKXON6d6J5Ke9d9BE-y2z6THyvGXJ3w2X6HIlSP1Yx67Y9YIXiQKdORUGpLiD5lQ_57
9NKfe2RkGNQ33Iirg4hWCDLpd8U73bLX--_x-uzcxzPT-0xLQSRygP94FY81FUfZxLBwB4jWjaW8g0elpwWvEIJyGqOoL6XAA2LKLILm2IQIyBaxAn0M-lzg
4cZ3pb7MxDNOG8GmFpJ4_07Lun6v4NGNI8A141cQCZUah2A18zxJftohaAAOc3wbJnPZ-co-Ng03M_wq9P0lzBk558A4YLE93534-fJMuWlTGPFsKIehG9Im
bDvWKCK-N6SZX1dIIXc612cXLnEaQICbX93jr6k0E3OPrFb9mStDpJC
}

