sprite $ninja_100 [86x100/16z] {
nPY9RlEw3eIfVI5dylvlUr6BZf3MkN-Q1ZZi9WZ0rp79iQZ8Vn-feuRF8aCr4iH87vGv0837zooVOPR9nGH1abh3tvbAWWJ8Wtoisz-uQJhJfUBuDgB7zslK
iPY0QoLFkEPteROeJlQq-X9eRq6Z0Wlgl-wYbrhhxoXLaWzKyFpZts-edRm35tvpxxf_dTlY5NVg2VILLyt2BwdtwhWm7h6e-o76BwNYvYYiM8jDzSPzBwiE
NlIfzfWGpjzHtQ1U81krbDODT-UQZjPA-Lsvidk8fBOSSjVT2pfhoRcKKdByPLezaLfZh9DRzMojwxRm2BznG3iuFOMYs2rWEe_4xjwWrL_e7QJra8RRw1IB
kuVtRtiTQrzCVV2Hvzc5ttV0-YgqQyoAUsFHOxVizfcLbv-_ofXz4dUj_6w5jMKzlLokd4B9WxZhmMCuLdj9EONmYse1eAcRwMVib-IjlopM2Ejj0hncxfBD
5b-tmApLJjuLsEPe9VtAMdEMwfQ_PkwJt7IyUegdg5ub6wrFt7v07_wKrwZHtzWzjtcbTTljHd2-fZMi1csn0xpEgyrMkv5cBqz7bJoO16tKd7Fjqmw9Auyb
Egc06AzMB4oCK45eVYR4znLabrUnCKm29KxJUgabTkFuelxcF4m0RZqOIQ0dtnI9RfBL8lEWQderiJWoAtKixXhKceGc8i5FBwj9b23dgzOQu4fOgdOx43r6
Ys8fpULLJH94Z03jHIXx0u_9DqhiTzUBd7vJRtnRp_GQr4O0EIGRnfWBHPg8-HapvnYSwtX_9G5PmTbL6g0YMObJ7xj80qdVw44YY7zDMgaq9S5HgI9sJ6QX
33Cp1UVHkqK1KzWy1lX6GvBd4UlTyBNU095uYFEe_JHcRDdt3gdC_x-LR6Llf440GIGJzLzJCwg4_mC5Rm2rfvM4BsgensGIjfrqrisGPF_ujqe2raiPN7N1
OQ9gHDqt91AqvjpGGEH_FCgiAG_pIMeGEIOHoUS5g1Zl1tYFwpbWNulqLExG59lvF5ghWQXYXznEGdqSX7znJd3LCjGsdsMrXmu2DchAVWPs6Hf4akI5-n6M
f4ZezQcpIb1eIxdsoLELIgH5QTQoNb2fkQF8BCRur4yjrULBlvo1IAAmU6G0Lrh1Bbe7zNcrsiDbfovx9dAAF1aqI0sgbInFVJNtmGbgFbQ8GO4cqIw50dcY
6EmfL7dROzFCZbSfDo2EUQsrAcSdStZkktq-QzH5lLaBIbgwx052oMomqA-n7OHtezcCdOHZOYKu9d6TWz69N75zMFhaqr8KIJ7JQp684G1mWBYa9d0cCCd5
d368czqq-Y5_AYqJH6u0-0JQEr4CI3BdTsmWICueAnemUobGcGGj7e0BC8qP68DWbihwtLSaW2Z1arn3-69NwGJOEdajzbO7CGWmIR9oLQllcy6Ab8DMWDkr
jRARZb7gl7Ypik_9oHUnIG11pd6T0HGZu7VkBsXqmWeGUCnrHX59IGxVii5k-1dQpmjTaYOIzV7L1R0zGDiI7uFeiXY12wb-VgF8bmRxTat-BdKiLFZYOh-i
lqtPpGwbnXRYkfu_Jd6WFfHfNtXxJFXUApyDfgvDzj15AcvOPrhUrUgFe-2Y436CMDpAVBowsEH1_uAcq4aZpespi-e2glcCVZvoZ1Qgdu1y46lU5aFw20Ca
lNH666OMAKwLKFSdRKjHw5CQOVnEnGqqOafcwgxoL3IFBCITWP2dTylwdfL5EdnZGrsOYYZAFMK7k4TdJPKTSHXT2mYZIHZ4D-gX_QOYYJnmZaJReCo7pefj
wV7yLf793TrYBOhCkqvWFVeERJy_R0VEBeyIT4yOdlF3Kj9v2W1wbiT821UVZZi621AL07Opy0RM4qe2TdKzlfffubYr1f0bdalIwLt2F83FFuWEyse_DcUm
IZuMkpPJqls2SCbSs72rdKy_T2ax0oHDgddQXpoD4DBbVgDNOuPsm_tkRl7U-Yfln3ZLQfhx1LRdkMtn7MhGfP2q2kyfgdbwWInlHRYdSy7zhoUWofjH5X9E
VVW0laju5ziycTZGjToLUhzYEmFd7zj2twpOpi4-5vB8NxWH-4ubMUIFKM346UxQBd-E-ZXdUAN-76CtxV5jylS84fJ4FQT0aez4CcmewcUWGSgzJaINZqMx
3pKg7uovIkMU-bZO6kkoV3IY-O3msSW4cdmy6cUGpqSByX_6_m
}

sprite $ninja_200 [172x200/16z] {
x9c7Sgiw60P3HzA_o_k_xJNZqOJRpCG-mgVaI-_hvLD1-VZbyfq-bRN_-EYwdvvqAe3ayMS7xPOG53NcxYS67PDiWWeWQ_-JjdGk2g2Wga2UVZxI8L652a9L
-zDLOIhyRpJMuUUv-24FeaJvAMZx9HGVWA9gUNjnkpKazB7MUsAdVLzt9mGL_va3AwXiOhpFxLWgbF_Bgf_4G8pTUou_IYNxVw-eeWIAxrWUXgmWUEBLgbT1
BEE5FkzDZGr4lXYHYrkxe2ZFH9VwY2z3HV49KdIz51ML9o8Iibw5EeaWw1Ei2BXUqu8HGG1ziWF8V0Lg7oAgWazwHOOBn6PH4FHPLi6uPWkWZtcqll81SsdE
6Y9ujgjI7aQDrfLTDl2SH43r4QlqRHTOJb5LphqAcDfg5K7a90edVGMwfcr5yOn1FPryHKfBrX55yTIfdXKMRRhI9X0ulstDwpBFQpcvPrnQie9Ius708oWH
QPdwhXldL50hbrZvL26YvDpqJAP7G1Mh71NGoEkq7sGEEoQYbLC1WPrmNQRXaiFE-HCHHIfJdljkvrpAWLwjl71_A1ScLJOEpieox5-xSQ9RPJjefQnxB_fn
Mb8k9I9AoMcTXwQi1OyD3StZBgkRKgNJOuqbqerpN59mq2mWMsaf-j1HmPZsvlLpHZ-xQtsDiOxzbA927dzO31XRBh2Y8CJz7FW6gYfwb0P8cc-SLJSUZAEn
eR2s6cUTrHanxMDfAbKMWa85Xfn3qGE_H--XeLYM9hIzga0PzuzMH9wE2ehHDPkopFi07hEYBv1MqM5gSO2bMdRIEH3aXQY2YAK1gy1SIK70rxrAWst1UZyl
cSjXCBqGw-iMgEoNVmeaey1hNjL6_x3hSYpxQuXbp1lukbWZJIscreYRr07IE6J5rr7BqkWq8wSRxrBcRaWAyXogeaIQnxxTwZhjExx-eq-nYQBoDLgLcljE
AwtBF4rzruPuEQoaajTKlZoXeWTgPOiMYgSm54NACitbXUN0oYp--9cWNy4D9FwYvKeK6uTL8EW-0F__rxu38RFkPbkxJRDNhpYJqHZ1W7QaMEYXOkMg14zg
w1Tss66hFnBc-JmCY9U86o_HQ2NyYkcgYLp5q5YyYdq4LvYqUCafXj-h3v6OjVqR1dl8Uiehpzx-_wZb_s1_qyOQ2OAMLRwO2kAvRdSVaUR_IOvlBs1d1gn6
A9-rZ9ScjwEMU5VK_dflhesf0AHvU1cozJTgAVq-huRJtwl8RnZSRMKRNenIpo6aGNAhG73-NUaxm0vySnomg--rxmam3v8dUlM-ygNfpF6jBKySp7B8tczc
GKYTn0tEkxnU7JZzCnE-tHnYDc0ZQxLjYS5jLjspSyk0njitWynEn4Y0XVPYtjQ0q6X56KHR4PQPyRTiLs7HGOLYIb1UUgkrZKbRVkTlZqiqMuvNL6KkYllx
jrWrT6H9A_56Vba_3BdsEMdJk9BKNZ-YjCzmcihB-xF1jMI0OJ8VB2JpcicXVu3s-F8E4CrUu_l1iXG0BBR0juUNFY8-tqFRszxxA-vK0I1EEQ-V6lFJcnZB
8A6bqRwBeF8h8pc5MOkjYMi9MGuU2HzCSfed55K35Zt2BndmQzsY5bxsYGlNrq0tke_5vH3FMn2XiNscvkYxlOmDZWA4i-OM-NjwkEbVU9cFF7zU_nw0HLdz
5S56ybJ0zbSVQ1Ev39AJ9kV-UTAMY4ETDG4qdvP8RuRAmXii1m1SfQ9_KUYqfwCW09wnAC-r-8PjsltOl0JhRs_3DX5Z1o-ZZpxvt5U-r1W1K9hYBbVBnM_5
lh4AqtkXiaYOBDv8tsWz8rYanTH5iJBNcFkPKnbI3xbJU1T3_Sq2O0dPhYwwY8xM2saZR_7ABCUbyN7DL4XE4OVtGZrO8ix5Z_4QKbAEAb_xMaOyin0xvS8L
RGjU_vvOfRqLgW98aEtoGUzj4eeXbbA79_Ysg8itSKg5gTPQ4gOkgpK2Ur_WyURUYt2HehcHBAnXXI43w0hmLaM_LWjM0Ejp-jApONrRxfB62lznQ0wmz9NN
TouvjkCsBoqvEXU2opPQzIFlyOinbCcY_RrOcHi0DXjR1DHkZF35qZ1khICyhC2w3Zpiza2sTr9_3ZN4sarn1vE6W6wkbknoNakPQtKguka1jhdmE__Y6yOK
ViCsWB7i2dL9geV48ZAMUbd-t1HZ6-T33kPhfQ_RnnYZZpx76DLpihZUmiGVqBaQqtBjFYNXpIRsW-Kb6s4myuWVyjL9h_F-kQgSy9CRQMlElQQ8sLRI1qeb
lwWSNdShNfSoTQtRjw5gnN_jy-jqOjjQ00VB-KSvvthttuzMZNQaTDEnePOjl7wZ9mSMjtu6DVzWMjmU1fUf1T1cbj4gwBl3fwVpCBNUFd4fghx6zw56ZuMB
qfaHqd3haTYNh38VBqjP3VBLJXpsbqji2_MJ1Bk9LoIiG4FzKxcKMVpgsQp8y5Tj7OTxQlm2BMRpEU8Fwhxp5QWdX3KJvXRfJCIIDoQqBD53kPS0xWYk_THH
djdvmJBHhlG37t2Mg4TSBvuZSysq1XLnCndCZo87WsiX3XFD1kp3Ravwtwk0eJmzYeCQYAY6qnLpzJBtE5PK0CWTVPv4I0xXaGmfRGluwbyV-ovCkgqI7xpn
vOZKdgUep3q1O3JTMfx1mgDYPUQ3DD5CqYutoLgCLkfGcyCfTSHhsZ2NkRFS4MpnSyD9zV68c0xSuAeuxM7ZTUfa-GGDYLySsuUHAqVet0hBLHJ5tojKaVnG
0qEwfNWYTd6QBU4QmH9chr-lLqya3_e5mfjKrEU6_7mIFaXJ8z2us7Eic1ePIKPB1C3D3FQ4saOuvDxuazAG4I3L0O2HScHcVbgbDC1abNhBY9OMic-s8hJD
d2O75ysqcLf2tHVkjkOfQUQbNWXt6C97VOeL48c5bId8TH1_66QKCLQERObdiv0iiuPAD_i5J25EMYPcO88Yp1AV7nzinqW8c9lL0jTHB-vrAHRHMlFrT4va
Jhx7gtHc2tsHEKKj8hwJkI1Wwlj5Fy3bbiKjwBGI3o_nXUKEsCEQ-eGGIVegOifFibSVkl6kPBE2mz92ekMLe86z1vKzc4HcGZKvwVacQricyoL6RX4aipF5
Ga0wsBnjYAGVtv7h_h6aYi_8twKrdxmuO5umE0KwyozHOarsLk8zEXJ9JLzhBgqJViTQyKLS1BeE8feuH3P2ywWJO8BCJnuoKPyGutSDxIhCnoiIc3bXEyWx
_fh4efMw26tc-cZa3OjsIM7ezSCteCfL0k9wZL3FpoqfK3DODEWYiimdioEfwaL2reirW80F2pNHQFvgC3L2LZxyrte5Kqg5pay4swjUjiFAkG3mcMAZSVPg
a2fe_k-VYxq1wEP8nt0Vgm_hXoBCV6I0yKW6ONmyv-QuWaTxmyQoggou0qDepy_mDfZQpzMRz0clvN2eld7Freo_dH6wPBKlEmpu2FBuN2naMMv8UjOk2Wk6
ZtFKieQyS2OhLztg4yhhnn7I9h_s1yJQErrZQMlHCW3UnDiDo-atkv4746IdUs8layquL8VRYgb7WvdCX5clbs28vHKyy5QMxURutzx4C5gtJAQPEmSd9LQt
Ndg6LGheypfKsGdROBf1RMEVNPFq-k2-qDwrCXHJn4ISV9W0duG18Gldc6N7M4YtR3W_t2OKNvpLMXXfb4BC0nGh7xex5XCvFOi36OdL36CvjrbaORfbOfaC
yelYLasOW6PGPzqtR2a3U5o-hu9ZB8UKaNO0Ms8xljmKcfzago-qB3sOYuEMOiMpWXvGxScFqgmKzOFITXXNhFL6ZUYDdl72vFvJyBpS0VJ3a1aV3i2kbncQ
RUKpk5J5-lKWIN0pvolpF5k3T_e9Kp3huCcSTbW5K5UjBeRN-lORZNPRd8HVfxXJUw_kStNJt1q-RJaQaZx7n2gq1fu2azbgdtSlRpUP6gCkXTkqgTuIgxXM
rWtYbx0wjjven_GThiATkhojEjiphXbktLf-WZD7-ynF0cUbDLchx1CSqx3cpq06slb5JvP26ZbSYuZSpmK7qcNI--3LuXvPj_RCpF_M8drvW0uX-haArCcW
VWXlRYFT8jPK4AiOLlrrqAeqMzfRwF79kNah1z8d2s-RQZEmUsRHi5AL-_jhJVQ1OLq98Qv3tZYCxH4-m_ePhLr4n2Mzl4Zsr7lU20GcJbBht0E3nQkIRC1Q
TcnutQF_Abx5wLNMJ2VNrNXzahGS7DV9NbyKgMSGZ_DWVnHyoQk8q6keFYDaUU5sNH5WF0AhyAYL5RdSwcu0eQEF4lZFztzX7VyST2IHpQfVeawLx47F3iFD
oE9QNUKmedR5zOLSIbjn-36NDj5yyl_EaMzK5c7cajUZWrgKdEFrUo3WQFyjvpgKBLM1u23eLKBx_r_x0aKNY94NbAtjpK5F5-5EJyoZkF8BZrErotbQVB38
Aqg54tqDvMtKYsXftHjzG0Jfnjq9SKrgKG6mj6INn3-nllImLx82Kj1b25P4-nQ1nS4K81CdChYuqmllVwqUdTwmDLkkUdRU_GNhW91OqdRJkx8YOcAYgu6g
TPaBsFvYmym2yrAqPxEu1XVPM2FKX7M1KxOpA8CmNEGbRjwFF0yGmlluIyujkI5MQIfHDWV6YIe8u2aIzdwEdldINLyMdOv8qr2bXSPOHieRQs1EbxlMZjcw
SSejXPO_cOsyUJQ22p290gE5pMsy8SxpY66CKTZ0cW4K-ngigGuiYHCihjtd0tErjiCwHJdViAvC94TrFI506MoFwRQ0iXx5gyuIJCRcn_Ok_c1z22ePi2Rx
nK203m5w5qa5hmaBqZQmfxP0ppmwvMUn6nk8podxc2dNJNC_0yK6mVzsDaNSNCWibGnAhPdfJCJ_qsh0HYuHTLL68ECpzy1T9Pevm65F5XmdfThargHO_9tt
lE0QBWUeZ3UUkScxZ8r5PsP2X-V0NEZc78GcLTPpdyBTZ35JWsKdGJMJ3fQB53_fFaXCPsaXIL9cI6NHjvaDyt0cDHsjG2n5PLd0BLMlDjupFN6Qy0TjG1PU
xg16nvSJHSNJH9bx7S_sca9qPnaHditUriywqqOBlfu0LtQ-36oH61qhb5Neh3bxN4WOrDEE9jHPCA-uhMTawM5FmlgOKFvWfTL3ECoFXoMWvk0qMv2kk8Pr
ISk2Y2muxAWQs_Mrt3z1OKDQl52Hh0Skpu1JSVd3MeLYJ7EvU_3F__C85BgByt67co3n47KrjWq9LaixJ4jsVAY-e296PNHSiqgFaXWq0s505bIqfOqOGyDp
fkA4vDdudHO5NKDHfcoBH-gDL_-iwz79OzGQELK2_Eno7JIU2n-XdlYN8_Jqq5BJnyyDZ4vw8sAh73GFWXFbMAIQBvOH9Q_0xuUeZj4ngVtHc8BNXSjDHtEK
jp1uO1UpL3fWVmQ2CLIhML6jixo2fAuoA5sMLDIPm4BAoQ-SnqqmMVmI9XISM3glVTYTLy_GJVPKgBZUWffvwpEBIvJQIikx659DytEk356iexmD7Vt2jObh
Yho-3zDs1XWXj_85Vi0hz8Xhr5XmWto21NZCbPwCaO_W6dFoy9DyXS6ZZUqity5mSwyuvz25LV8XfbmnSvsJPsVTbvY1M0XzOmGOLVeKgUpuDYTF7VWXsDTv
SrnPDlOrDAx8vaY0z82Vot8Yv6xe7a2DVI5Ql9OUm1ZHuImrXX96wGMAouUJOfTP-e7E8QE3TOMLdZ3bgNFxc-MLT8LvPGzb1haFqXVKmjZRlj91UiD0qx_1
KMbjf_QhjtjLwyD20_9UTGSbx4CkJAlNqYbOEf_LrIITGYcF4957kVKBlH5NmKhF61aJPgzdpvYBLEWWdSC5BkqelKCboRLEqZzqfCfKM-SOSpomVynWoK__
KDQFyijWaby4Idvd_0a
}

